### ISSUE TITLE
Instructions for go get fail.

### ISSUE THREAD

**Issue by andrewchambers** [dvyukov/go-fuzz#1]
"go get github.com/dvyukov/go-fuzz/..." as readme suggests fails. One error is spdy was deleted. perhaps you can test from a fresh GOPATH

**Comment by dvyukov** [comment]
should be fixed now
thanks

**Comment by dlsniper** [comment]
Hi, this still happens with the latest master and gotip (0bcdffeea6e42d57ac02f11e099652cbd69b427b) Not sure if it's the same issue or not but maybe the GopherCon slides could be updated to the info in the readme (use two different go get operations?). Thank you for building this amazing tool!

**Comment by dvyukov** [comment]
Should be fixed by 76634ea8afb2531d576ce6e5318f849d45cf5838
