### ISSUE TITLE
Is CGO supported at all?

### ISSUE THREAD

**Issue by mirtchovski** [dvyukov/go-fuzz#102]
i have a very simple case i'd like to test. something like the code below. the fuzz builder builds the zip file fine, however when I attempt to run it I get:

```
$ go-fuzz -bin ./p-fuzz.zip -workdir .
2015/09/17 06:54:57 bad input archive: missing file
```

here's the very simple code:

```
$ cat p.go 
package p

/*
#include <string.h>
*/
import "C"

func Fuzz(b []byte) int {
	s := C.CString(string(b))
	if C.strcmp((*C.char)(s), C.CString("test")) == 0 {
		panic("")
	}
	if len(b) > 4 {
		return 0
	}
	return 1
}
```

**Comment by mirtchovski** [comment]
i've also tried to extract the cgo bits into a separate package and call that from the fuzzer, but no worky.

**Comment by dvyukov** [comment]
This is a dup of #101

**Comment by dgryski** [comment]
If your Go code is just smaller wrappers around the C code, consider fuzzing the C code directly with the original http://lcamtuf.coredump.cx/afl/

**Comment by dvyukov** [comment]
<shameless plug> or with http://llvm.org/docs/LibFuzzer.html </shameless plug>
