### ISSUE TITLE
go-fuzz-build fails on github.com/golang/freetype/raster/stroke.go

### ISSUE THREAD

**Issue by pmezard** [dvyukov/go-fuzz#103]
Hello,

Running go-fuzz-build on github.com/golang/freetype/truetype fails with:
```
workdir: /tmp/go-fuzz-build120675630
workdir: /tmp/go-fuzz-build334498485
failed to execute go build: exit status 2
# github.com/golang/freetype/raster
/tmp/go-fuzz-build334498485/src/github.com/golang/freetype/raster/stroke.go:279[...]: undefined: golang in golang.org
```

It happens because the annotated source looks like:
```
_go_fuzz_dep_.Sonar(v1, golang.org/x/image/math/fixed.Int52_12(fixed.Int52_12(1<<12)), 662402)
```
instead of
```
_go_fuzz_dep_.Sonar(v1, fixed.Int52_12(fixed.Int52_12(1<<12)), 662402)
```

It comes from https://github.com/dvyukov/go-fuzz/blob/master/go-fuzz-build/cover.go#L288 returning the "fully qualified" type.

Removing everything from typstr before and including the last slash fixes the issue. I can make a pull-request if you want but I have not dug enough to know who to blame. Maybe that is a bug in golang.org/x/tools/go/types.

**Comment by dvyukov** [comment]
Thanks for the report!
I've added freetype and truetype examples and checked that they work now.
However, if you want to fuzz truetype, add some real fonts into corpus directory.
