### ISSUE TITLE
go-fuzz-build: "can't find imported package golang.org/x/text/transform"(darwin amd64)

### ISSUE THREAD

**Issue by bigwhite** [dvyukov/go-fuzz#109]
hi,
 I met a problem when I used go-fuzz-build on my gocmpp project, details like below:

```
$go-fuzz-build github.com/bigwhite/gocmpp
can't find imported package golang.org/x/text/transform
```

I have checked the env for several times and make sure that golang.org/x/text/transform is at its right place. 

Any ideas?  Thanks for your time.

**Comment by DavidVorick** [comment]
have you tried

`go get -u ./...`?

Also, there have been a few times in go where a library/utililty didn't upgrade from 1.4 to 1.5 when everything else did.

**Comment by bigwhite** [comment]
I found the reason. It seems like the go-fuzz-build does not support the vendor mechanism in go 1.5(and later). I turn off the vendor experiment flag and execute go-fuzz-build again, and it works:

```
$GO15VENDOREXPERIMENT="0" go-fuzz-build github.com/bigwhite/gocmpp
$ls
LICENSE			activetest_test.go	conn_test.go		deliver_test.go		fwd_test.go		receipt_test.go		terminate.go
Makefile		client.go		connect.go		examples/		packet.go		server.go		terminate_test.go
README.md		cmpp-fuzz.zip		connect_test.go		fuzz.go			packet_test.go		submit.go		utils/
activetest.go		conn.go			deliver.go		fwd.go			receipt.go		submit_test.go		vendor/
```
