### ISSUE TITLE
A minimal release please?

### ISSUE THREAD

**Issue by jeffallen** [dvyukov/go-fuzz#114]
It is too bad that this repo has grown to be so huge, as a result of the examples, I guess.

It would be helpful to have a minimal release available for download so that people who just want go-fuzz and not the rest could unzip the source into their GOPATH and skip the enormous git clone.

**Comment by dvyukov** [comment]
I've created github.com/dvyukov/go-fuzz-corpus. Help with moving corpus to that repo is welcome.

**Comment by dgryski** [comment]
@dvyukov Moving the entire examples directory is probably easier. However, if you just want to move the corpus directories:
```
for i in `find examples -type d -name corpus`; do
    d=`dirname $i`
    mkdir -p ../go-fuzz-corpus/$d
    mv $i ../go-fuzz-corpus/$i
    git rm -r $i
done
```

Of course this still leaves all the examples in the repo.  Fixing this isn't possible without rewriting history.

**Comment by AlekSi** [comment]
Dupe of #88.

**Comment by dgryski** [comment]
Will be obsoleted by https://github.com/dvyukov/go-fuzz/issues/154

**Comment by AlekSi** [comment]
See https://github.com/dvyukov/go-fuzz-corpus/issues/1. After it is done, history is this repository can be rewritten.

**Comment by AlekSi** [comment]
@dvyukov Rewritten history is pushed to https://github.com/AlekSi/go-fuzz. I also added a note to README about that.

**Comment by dvyukov** [comment]
Done
This is resolved now, right?

**Comment by jeffallen** [comment]
While I'm here, just want to say thanks for go-fuzz one more time. It caught some bugs at work today. 🥇
