### ISSUE TITLE
go-fuzz does not work with Go 1.6 / tip

### ISSUE THREAD

**Issue by davecheney** [dvyukov/go-fuzz#116]
```
% go-fuzz-build github.com/dvyukov/go-fuzz/examples/png                                                                                                                                        
failed to execute go build: exit status 1
import cycle not allowed
package go-fuzz-main
        imports github.com/dvyukov/go-fuzz/examples/png
        imports bytes
        imports github.com/dvyukov/go-fuzz/go-fuzz-dep
        imports syscall
        imports internal/race
        imports github.com/dvyukov/go-fuzz/go-fuzz-dep
```

**Comment by xih** [comment]
@dvyukov Still getting this exact same error on windows though. Any fix ?

**Comment by dvyukov** [comment]
@xih Are you sure it is _exactly_ the same? Or it references a different package?

**Comment by xih** [comment]
C:\GoPath\src\github.com\arolek\ase>%GOPATH%/bin/go-fuzz-build github.com/dvyukov/go-fuzz/examples/png
failed to execute go build: exit status 1
import cycle not allowed
package go.fuzz.main
        imports github.com/dvyukov/go-fuzz/examples/png
        imports image/png
        imports image/png

Looks the same to me.

**Comment by dvyukov** [comment]
@xih This cycle is completely different from the one in the issue description.
Please file a separate issue with reproduction instructions. Thanks.
