### ISSUE TITLE
go-fuzz-build: Build only when out of date

### ISSUE THREAD

**Issue by tv42** [dvyukov/go-fuzz#118]
Creating the `*-fuzz.zip` takes a lot of time even on a simple project. Yet simple checks like "only create if it doesn't exist" easily leave us fuzzing already-fixed code. It'd be really nice if it behaved like `go install` and friends and only recreated the zip if the inputs have updated. I'm sure implementing this once in go-fuzz is better than every caller implementing a bad version of it in a shell script, which is what I almost just did...

**Comment by dvyukov** [comment]
I agree that it would be nice. Pull request is welcome.

I think eventually go-fuzz instrumentation should be merged into Go compiler, and go-fuzz-build logic should be merged into go tool. That would solve lots of issues including this one.

**Comment by dgryski** [comment]
WIll be obsoleted by https://github.com/dvyukov/go-fuzz/issues/154

**Comment by josharian** [comment]
I've made considerable progress on build times. When `cmd/go`'s `-trimpath` plays nicely with the cache (https://github.com/golang/go/issues/31896), it'll get even better. I'm going to call this fixed for now.
