### ISSUE TITLE
More breakage with go 1.6 rc1

### ISSUE THREAD

**Issue by dgryski** [dvyukov/go-fuzz#120]
```
<dgryski@kaepora[go-fastlz] \ʕ◔ϖ◔ʔ/ > go-fuzz-build github.com/dgryski/go-fastlz
failed to execute go build: exit status 1
can't load package: /tmp/go-fuzz-build640820997/src/go-fuzz-main/main.go:5:2: non-standard import "github.com/dgryski/go-fastlz" in standard package "go-fuzz-main"
/tmp/go-fuzz-build640820997/src/encoding/binary/binary.go:22:8: non-standard import "github.com/dvyukov/go-fuzz/go-fuzz-dep" in standard package "encoding/binary"
/tmp/go-fuzz-build640820997/src/io/io.go:13:8: non-standard import "github.com/dvyukov/go-fuzz/go-fuzz-dep" in standard package "io"
/tmp/go-fuzz-build640820997/src/math/abs.go:5:8: non-standard import "github.com/dvyukov/go-fuzz/go-fuzz-dep" in standard package "math"
/tmp/go-fuzz-build640820997/src/reflect/deepequal.go:7:8: non-standard import "github.com/dvyukov/go-fuzz/go-fuzz-dep" in standard package "reflect"
/tmp/go-fuzz-build640820997/src/strconv/atob.go:5:8: non-standard import "github.com/dvyukov/go-fuzz/go-fuzz-dep" in standard package "strconv"
/tmp/go-fuzz-build640820997/src/unicode/utf8/utf8.go:7:8: non-standard import "github.com/dvyukov/go-fuzz/go-fuzz-dep" in standard package "unicode/utf8"
```

Looks like this came from https://github.com/golang/go/commit/4223675913762a12cd23871fbd003d8a68cb49a1
From the commit message:
```
 Enforce that no standard package can depend on a non-standard one.
```

**Comment by rsc** [comment]
The problem here is that standard and non-standard packages are being mixed into GOROOT and breaking the convention that non-standard packages must start with a distinguishing prefix such as a domain name (or something that looks like one). The fix here would be to put go-fuzz-main into /tmp/blah/src/go.fuzz.main or any other directory where the first element has a dot. We could also consider detecting - in the first element as "not standard library" but since this is such a special case it might be better to fix the fuzzer.

**Comment by rsc** [comment]
Actually my suggestion only addresses the first error line. The others are real and intended as errors and subsume the first.

If go-fuzz-build is making a whole copy of the tree anyway it can copy github.com/dvyukov/go-fuzz/go-fuzz-dep into $TMPGOROOT/src/go-fuzz-dep and make the imports say just "go-fuzz-dep".

**Comment by dvyukov** [comment]
Thanks, Russ!
Tested with 1.5 and current tip, seems to work.

**Comment by rsc** [comment]
Thanks.

**Comment by btracey** [comment]
Is this broken at tip?

````
brendan:~/Documents/mygo/src$ go version
go version devel +7177cb9 Tue Mar 22 17:30:30 2016 +0000 darwin/amd64
brendan:~/Documents/mygo/src$ go get -u -t github.com/dvyukov/go-fuzz/go-fuzz
brendan:~/Documents/mygo/src$ go get -u -t github.com/dvyukov/go-fuzz/go-fuzz-build
brendan:~/Documents/mygo/src$ go-fuzz-build mathext/amos/airytest/fuzz
failed to execute go build: exit status 1
/var/folders/s0/2lsmv0jd7x37kkxmc_q6wyj80000gn/T/go-fuzz-build577780626/src/mathext/amos/airytest/fuzz/testairy.go:11:2: non-standard import "github.com/gonum/floats" in standard package "mathext/amos/airytest/fuzz"
````

The direct code ran is http://play.golang.org/p/CsBXOqzz_I, though that's not enough to reproduce.

**Comment by dgryski** [comment]
Make sure your go-fuzz is up-to-date.

**Comment by btracey** [comment]
This is what the `go get -u -t` commands do

**Comment by dgryski** [comment]
Oops missed that. The problem is the lack of '.' in your package name (`mathext`) makes Go think it's a standard library package.

**Comment by btracey** [comment]
You mean go-fuzz. Go build works just fine.

**Comment by dvyukov** [comment]
#rsc Russ, please take a look at this comment:
https://github.com/dvyukov/go-fuzz/issues/120#issuecomment-200399246

How does go tool understands that "mathext/amos/airytest/fuzz" is not a standard package in this case (no dots in name)? Is it because it is under GOPATH and I put it under GOROOT? Should I put everything under GOPATH instead? Or preserve GOROOT/GOPATH separation?

**Comment by rsc** [comment]
Standard = 'no dots in first path element'. The message says:

    non-standard import "github.com/gonum/floats"
    in standard package "mathext/amos/airytest/fuzz"

I don't know where mathext/amos/airytest/fuzz came from, but assuming it does contain an import of github.com/gonum/floats (that is, assuming go-fuzz is not adding that import), then that package won't build even outside of go-fuzz.

**Comment by dvyukov** [comment]
Thanks, Russ.
@btracey I guess you need to change your code to comply to the new go tool rules then.

**Comment by btracey** [comment]
@rsc @dvyukov  What you say doesn't match what `go build` doos on my system. I compile code daily that lives in `$GOPATH/src/myfoo/maybsub`, where myfoo does not contain any dots. This works both on tip and on 1.6, and has worked as long as I've been using go (1.0.3). 

If it matters (and hasn't just been a miscommunication), here's an example from code I have been running today (I moved the mathext code to work with go-fuzz -- mathext is what will hopefully become gonum/mathext to fill in deficiencies in the "math" standard library package)
````
brendan:~$ cd $GOPATH/src/sfi/miso/beliefopt
brendan:~/Documents/mygo/src/sfi/miso/beliefopt$ go install
brendan:~/Documents/mygo/src/sfi/miso/beliefopt$ go version
go version devel +c1892b9 Wed Mar 23 15:51:55 2016 +0000 darwin/amd64
brendan:~/Documents/mygo/src/sfi/miso/beliefopt$ go env
GOARCH="amd64"
GOBIN=""
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/Users/brendan/Documents/mygo"
GORACE=""
GOROOT="/Users/brendan/gover/go"
GOTOOLDIR="/Users/brendan/gover/go/pkg/tool/darwin_amd64"
CC="gcc-5"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/var/folders/s0/2lsmv0jd7x37kkxmc_q6wyj80000gn/T/go-build230984717=/tmp/go-build -gno-record-gcc-switches -fno-common"
CXX="g++-5"
CGO_ENABLED="1"
````

**Comment by rsc** [comment]
Sorry, my bad. Rereading the cmd/go code, standard = 'found in $GOROOT and no dots in first path element'. Is gofuzz moving code from $GOPATH into $GOROOT?

**Comment by rsc** [comment]
Probably it should be copying to a temporary directory, not an existing
directory (the existing directories may not be writable, but maybe go-fuzz
is already using temporary directories as I'm suggesting), but yes things
that start in a GOPATH need to still appear to be in a GOPATH, not a GOROOT.

**Comment by dvyukov** [comment]
@dgryski I've tested latest go-fuzz version with go1.6 and current tip recently. And it worked without any problems. The errors you posted reference go-fuzz-main/dep, so I would expect it to affect all targets.
Is it still broken for you? I wonder what's the difference between your environment and my environment.

**Comment by dgryski** [comment]
I don't have any more problems with this.  I think you want @btracey .

**Comment by btracey** [comment]
No, it is not fixed.

I put the following code in $GOPATH/src/testfuzz/fuzzpng
````
package fuzzpng

import (
	"image"
	"image/png"
	"io"

	"github.com/gonum/floats"
)

func Decode(r io.Reader) (image.Image, error) {
	_ = floats.Sum([]float64{1, 2, 3})
	return png.Decode(r)
}
````

and the following code in $GOPATH/src/testfuzz/fuzz
````
package fuzz

import (
	"bytes"
	"testfuzz/fuzzpng"
)

func Fuzz(data []byte) int {
	fuzzpng.Decode(bytes.NewReader(data))
	return 0
}
````

Then I cd to $GOPATH and run `go-fuzz-build testfuzz/fuzz`
````
brendan:~/Documents/mygo$ go-fuzz-build testfuzz/fuzz
failed to execute go build: exit status 1
/var/folders/l6/mhj4qjrj4437b_lgfz9pm1rw0000gn/T/go-fuzz-build572361318/src/testfuzz/fuzzpng/fuzzpng.go:8:2: non-standard import "github.com/gonum/floats" in standard package "testfuzz/fuzzpng"
````

**Comment by jerome-laforge** [comment]
Hello,
with go 1.6
```
go version
go version go1.6.3 linux/amd64
```

And the latest go-fuzz
```
go-fuzz-build xxxx/yyyy
failed to execute go build: exit status 1
/tmp/go-fuzz-build049689332/src/xxxx/yyyy/zzzzz.go:10:2: non-standard import "github.com/go-kit/kit/endpoint" in standard package "xxxx/yyyy"
/tmp/go-fuzz-build049689332/src/xxxx/bbbb/ccccc.go:12:2: non-standard import "github.com/inconshreveable/log15" in standard package "xxxx/bbbb"
```

My project uses gb and the gokit and log15 dependencies are into vendor as defined by [gb](https://getgb.io/).
Normally my GOPATH is correct as the GOPATH contains directories list of where are the source of gofuzzing, the directory of my program (what I want fuzz), and the vendor directory (where are gokit and log15)

How can I solve this?
Many thx.

**Comment by dvyukov** [comment]
The referenced commit should fix the "non-standard import" bug. Please try it.
If it does not work, please open another issue. This one is really about a different thing.

**Comment by jerome-laforge** [comment]
With the commit, go-fuzz works like a charm !
Many thx.
