### ISSUE TITLE
go get for go-fuzz-build fails at tip with duplicate key "internal/race" in map literal

### ISSUE THREAD

**Issue by rjammala** [dvyukov/go-fuzz#121]
0700077782A:~ rajanikanth.j$ go get -u github.com/dvyukov/go-fuzz/go-fuzz
0700077782A:~ rajanikanth.j$ go get -u github.com/dvyukov/go-fuzz/go-fuzz-build
 github.com/dvyukov/go-fuzz/go-fuzz-build
gocode/src/github.com/dvyukov/go-fuzz/go-fuzz-build/main.go:267: duplicate key "internal/race" in map literal
0700077782A:~ rajanikanth.j$ go version
go version devel +1f7e3cf Thu Feb 4 06:19:19 2016 +0000 darwin/amd64

**Comment by dvyukov** [comment]
Thanks, @rjammala. Please try the fix.

**Comment by rjammala** [comment]
Thanks for the very fast fix @dvyukov :+1:
