### ISSUE TITLE
go-fuzz-build gives an error in Go 1.6

### ISSUE THREAD

**Issue by cespare** [dvyukov/go-fuzz#122]
```
$ go-fuzz-build XXXXXXX
failed to execute go build: exit status 1
/tmp/go-fuzz-build434284372/src/syscall/syscall_unix.go:10:2: cannot find package "internal/race" in any of:
        /tmp/go-fuzz-build434284372/src/internal/race (from $GOROOT)
        /home/caleb/p/go/src/internal/race (from $GOPATH)
        /home/caleb/src/internal/race
```

Note that I built go-fuzz-build with go 1.6 as well.

**Comment by tv42** [comment]
@cespare Try latest, I think 7076fcd fixed this.

**Comment by dvyukov** [comment]
Can't reproduce it with go1.6, building github.com/dvyukov/go-fuzz/examples/json, with CGO_ENABLED=0/1. Please provide exact reproduction steps.

**Comment by cespare** [comment]
I can't reproduce on another machine. It's some kind of bad state on my workstation, I think. I tried deleting my pkg dir but it didn't help.

**Comment by cespare** [comment]
@tv42 when I reported this I had just installed from master.

**Comment by cespare** [comment]
Aha! It is a go-fuzz issue after all.

The problem occurs only when the fuzz program doesn't import certain packages.

For example, with the following test program:

``` go
package sortfuzz

func Fuzz(data []byte) int {
	return 0
}
```

I get

```
$ go-fuzz-build github.com/cespare/sortfuzz
failed to execute go build: exit status 1
/var/folders/7r/pz2frytd23gb3pt4bwwshp1c0000gn/T/go-fuzz-build742525667/src/syscall/syscall_unix.go:10:2: cannot find package "internal/race" in any of:
        /var/folders/7r/pz2frytd23gb3pt4bwwshp1c0000gn/T/go-fuzz-build742525667/src/internal/race (from $GOROOT)
        /Users/caleb/p/go/src/internal/race (from $GOPATH)
```

However, if I import math/rand:

``` go
package sortfuzz

import "math/rand"

func Fuzz(data []byte) int {
	_ = rand.Float64
	return 0
}
```

then it works.

**Comment by cespare** [comment]
(It's possible this isn't a 1.6-specific issue. I don't have a 1.5 compiler on hand right now, but I can check later.)
