### ISSUE TITLE
go get could not found 'exact'

### ISSUE THREAD

**Issue by Komosa** [dvyukov/go-fuzz#126]
go get  github.com/dvyukov/go-fuzz/go-fuzz-build

(on fresh machine) gives _exact_ not found for error:

    package golang.org/x/tools/go/exact: cannot find package "golang.org/x/tools/go/exact" in any of:
    	/home/kokos/.goinstallation/src/golang.org/x/tools/go/exact (from $GOROOT)
    	/home/kokos/gocode/src/golang.org/x/_exact_tools/go/exact (from $GOPATH)

Looking for this package via browser ( golang.org/x/tools/go/exact ) gives the same results. I have copy of _exact_ on my machine, but I think that there is need to make code buildable/go getable.

**Comment by JakeMont** [comment]
Is there a reasonable workaround for this. I am also unable to `go get  github.com/dvyukov/go-fuzz/go-fuzz-build`, which is making me very sad.

**Comment by Komosa** [comment]
Discussion for this in in #128, for now only unresonable workarounds are possible - for example, you could copy some version of removed packages into your GOPATH. If you are interested in doing so, let me know.

**Comment by paultag** [comment]
Yeah, I checked out an old copy of `x/tools` and added that into my go env by hand, and it worked

**Comment by dvyukov** [comment]
@paultag glad that there is a workaround. Please say what revision you used for x/tools for the reference. So that people can do:
```
$ cd $GOPATH/src/golang.org/x/tools
$ git checkout $REV
```

**Comment by paultag** [comment]
@dvyukov I think it was `fe1488f8abd7e0eea44f1950dad93a6ff6880a60` but I don't have it handy, I'll give it a test later :+1:

**Comment by ernado** [comment]
Maybe it is possible to build a Docker container with x/tools so it does not affect $GOPATH. Currently investigating for proper workaround.
Checking out `fe1488f8abd7e0eea44f1950dad93a6ff6880a60` works for me now.

Broken go-fuzz made me sad :c

**Comment by Komosa** [comment]
IMO we should adjust our usage to current version.

And eventually use fork of x/tools in meantime.

**Comment by ernado** [comment]
Vendoring works too. Made a temporary fork to simplify deployment for myself.
```go get github.com/cydev/go-fuzz/go-fuzz-build```

I've used [glide](https://github.com/Masterminds/glide) with `glide install -s` and the `fe1488f8abd7e0eea44f1950dad93a6ff6880a60` is specified in `glide.lock`
