### ISSUE TITLE
"interesting" seems overloaded

### ISSUE THREAD

**Issue by BrianHicks** [dvyukov/go-fuzz#131]
I'm trying to use go-fuzz to find unexpectedly valid inputs to my parsing function.

The `README` says:

> The function must return 1 if the input is interesting in some way (for example, it was parsed successfully, that is, it is lexically correct

and then:

> `corpus` is current number of interesting inputs the fuzzer has discovered

But I'm seeing a lot of inputs that I haven't marked as "interesting" in the generated corpus, and are in fact invalid. Is this the intended behavior?

Fuzzing function attached, for reference:

```go
func ParseKVPairFuzz(data []byte) int {
	_, v, _ := parseKVPair(string(data))
	if v != "" {
		return 1
	}
	return 0
}
```

**Comment by dvyukov** [comment]
In the first case "interesting" means "from user point of view". In the second -- "from fuzzer point of view". Any suggestions on rewording?

**Comment by BrianHicks** [comment]
I would suggest the first change to something like "The function must return 1 if the fuzzer should pay special attention to the given input (for example…)". That's a little clumsy, but does it make sense?

**Comment by dvyukov** [comment]
Does this look better?
bf07c13b7900771eb3dbfbc5e20a382ed1de8c05

**Comment by BrianHicks** [comment]
Ahh, that makes more sense :) Thanks!
