### ISSUE TITLE
corrupted sonar data

### ISSUE THREAD

**Issue by ssoroka** [dvyukov/go-fuzz#146]
Received the following message during a fuzz:

`2016/10/13 00:58:29 corrupted sonar data: hdr=[0/255/0] data=863488`

Tried it again:
`2016/10/13 01:06:32 corrupted sonar data: hdr=[21/8/149] data=774004`

Might be related to https://github.com/dvyukov/go-fuzz/issues/145 ? Both seem to be around the issue of invalid sonar data.

Have any suggestions?
Update: I'm currently running with `-sonar=false` to avoid these problems.

**Comment by dvyukov** [comment]
Is it possible that the test program has some background goroutines?

**Comment by dvyukov** [comment]
This is a dup of #145
