### ISSUE TITLE
Compilation fails on Windows; syscall functions undefined

### ISSUE THREAD

**Issue by tdewolff** [dvyukov/go-fuzz#15]
Due to missing syscall functions this library does not compile on Windows. The following errors are produced:

```
λ go install github.com/dvyukov/go-fuzz/go-fuzz
# github.com/dvyukov/go-fuzz/go-fuzz
..\dvyukov\go-fuzz\go-fuzz\main.go:58: undefined: syscall.Setpriority
..\dvyukov\go-fuzz\go-fuzz\main.go:58: undefined: syscall.PRIO_PROCESS
..\dvyukov\go-fuzz\go-fuzz\slave.go:490: undefined: syscall.Mmap
..\dvyukov\go-fuzz\go-fuzz\slave.go:490: undefined: syscall.PROT_READ
..\dvyukov\go-fuzz\go-fuzz\slave.go:490: undefined: syscall.PROT_WRITE
..\dvyukov\go-fuzz\go-fuzz\slave.go:490: undefined: syscall.MAP_SHARED
```

```
λ go install github.com/dvyukov/go-fuzz/go-fuzz-dep
# github.com/dvyukov/go-fuzz/go-fuzz-dep
..\dvyukov\go-fuzz\go-fuzz-dep\main.go:31: undefined: syscall.Mmap
..\dvyukov\go-fuzz\go-fuzz-dep\main.go:31: undefined: syscall.PROT_READ
..\dvyukov\go-fuzz\go-fuzz-dep\main.go:31: undefined: syscall.PROT_WRITE
..\dvyukov\go-fuzz\go-fuzz-dep\main.go:31: undefined: syscall.MAP_SHARED
..\dvyukov\go-fuzz\go-fuzz-dep\main.go:78: cannot use fd (type int) as type syscall.Handle in argument to syscall.Read
..\dvyukov\go-fuzz\go-fuzz-dep\main.go:113: cannot use fd (type int) as type syscall.Handle in argument to syscall.Write
..\dvyukov\go-fuzz\go-fuzz-dep\main.go:130: cannot use fd (type int) as type syscall.Handle in argument to syscall.Write
```

`go-fuzz-build` builds fine though.

Additionally, cloning the git repository gives errors like:
```
λ go get github.com/dvyukov/go-fuzz
# cd .; git clone https://github.com/dvyukov/go-fuzz D:\Go\_projects\src\github.com\dvyukov\go-fuzz
Cloning into 'D:\Go\_projects\src\github.com\dvyukov\go-fuzz'...
error: unable to create file examples/gob/corpus/id:000000,orig:gob001660414 (Invalid argument)
error: unable to create file examples/gob/corpus/id:000001,orig:gob003084669 (Invalid argument)
error: unable to create file examples/gob/corpus/id:000002,orig:gob004976999 (Invalid argument)
error: unable to create file examples/gob/corpus/id:000003,orig:gob007769355 (Invalid argument)
error: unable to create file examples/gob/corpus/id:000004,orig:gob009259022 (Invalid argument)
error: unable to create file examples/gob/corpus/id:000005,orig:gob010917529 (Invalid argument)
[about a 1000 more]
```

**Comment by dvyukov** [comment]
Hi @tdewolff,

This must be windows.

I've removed the offending files.
However compilation still fails.

**Comment by dvyukov** [comment]
@tdewolff,

I've implemented windows support on _sonar_ branch. I will appreciate if you test it. Note sonar is not default branch. Also go-fuzz-build will build a zip file on sonar branch, specify it in -bin go-fuzz flag.

**Comment by tdewolff** [comment]
@dvyukov 

Thanks! I can confirm that it builds and runs. Not sure if this is related, but my output is like:

```
2015/05/07 20:09:06 slaves: 8, corpus: 0 (39s ago), crashers: 0, restarts: 1/1, execs: 4008 (103/sec), cover: 0.00%, uptime: 39s
```

Restarts stays at `1/1` and cover at `0.00%`, and the execs/sec stays quite low too (running for 10 minutes now). Testing on the png example.

**Comment by dvyukov** [comment]
@tdewolff no, it is not normal. It means that the test binary crashes whenever it receives an input.

Try to apply the following patch (need to provide a flag for this). It will dump test binary output to console. It can provide a hint as to what goes wrong.

diff --git a/go-fuzz/testee.go b/go-fuzz/testee.go
index dc17f0b..16ff488 100644
--- a/go-fuzz/testee.go
+++ b/go-fuzz/testee.go
@@ -117,8 +117,8 @@ retry:
                log.Fatalf("failed to pipe: %v", err)
        }
        cmd := exec.Command(bin)
-       cmd.Stdout = wStdout
-       cmd.Stderr = wStdout
+       cmd.Stdout = os.Stdout
+       cmd.Stderr = os.Stdout
        cmd.Env = append([]string{}, os.Environ()...)
        cmd.Env = append(cmd.Env, "GOTRACEBACK=1")
        setupCommMapping(cmd, comm, rOut, wIn)

**Comment by dvyukov** [comment]
@tdewolff
I've tested it on a Windows8.1 machine and it works fine (corpus grows, restart value is normal).
What version of windows do you use? Does the user have admin rights? Trying to understand what's different in your environment.

**Comment by tdewolff** [comment]
Windows7 and I'm admin. I get:

```2015/05/08 15:46:12 write to testee failed: write |1: The pipe is being closed.```

**Comment by dvyukov** [comment]
@tdewolff
This is kind of a blind guessing, but please try the following patch:
```
diff --git a/go-fuzz/sys_windows.go b/go-fuzz/sys_windows.go
index 5fc342a..c90bba4 100644
--- a/go-fuzz/sys_windows.go
+++ b/go-fuzz/sys_windows.go
@@ -46,6 +46,9 @@ func (m *Mapping) destroy() {
 }
 
 func setupCommMapping(cmd *exec.Cmd, comm *Mapping, rOut, wIn *os.File) {
+       syscall.SetHandleInformation(Handle(comm.mapping), syscall.HANDLE_FLAG_INHERIT, 0)
+       syscall.SetHandleInformation(Handle(rOut.Fd()), syscall.HANDLE_FLAG_INHERIT, 0)
+       syscall.SetHandleInformation(Handle(wIn.Fd()), syscall.HANDLE_FLAG_INHERIT, 0)
        cmd.Env = append(cmd.Env, fmt.Sprintf("GO_FUZZ_COMM_FD=%v", comm.mapping))
        cmd.Env = append(cmd.Env, fmt.Sprintf("GO_FUZZ_IN_FD=%v", rOut.Fd()))
        cmd.Env = append(cmd.Env, fmt.Sprintf("GO_FUZZ_OUT_FD=%v", wIn.Fd()))
```

**Comment by tdewolff** [comment]
No difference, I'm unfamiliar with the technique used so I don't know what to debug really...

**Comment by tdewolff** [comment]
The created executable in your home directory exits with `failed to mmap comm file` at go-fuzz-dep/sys_windows.go:23

The `err` from line 21 contains `(0x36d9c0,0xc0820020d0)` which is rather unhelpful. However `mapping` is zero because `syscall.Getenv` at line 34 returns `"", false`. Apparently communication of the environment parameters is going wrong!?

**Comment by dvyukov** [comment]
OK, got access to a windows 7 machine. Should be fixed by:
https://github.com/dvyukov/go-fuzz/commit/5725488536b003c07e3141f5c61ebeb83e63eed1
Note this is also on sonar branch.

**Comment by tdewolff** [comment]
I confirm that it works now (from the sonar branch), awesome!

**Comment by dvyukov** [comment]
@tdewolff thanks for testing and confirming!
