### ISSUE TITLE
Run for specific duration?

### ISSUE THREAD

**Issue by jesse-c** [dvyukov/go-fuzz#158]
We're looking to implement fuzzing into our CI. Right now it runs indefinitely. We're wondering if you'd be open to having an argument to run for only a specific duration? E.g. run for 10 minutes. The intent would be to run it for x minutes to catch any regressions and anything new. We're happy to  create a PR.

**Comment by dgryski** [comment]
I've used shell scripting to do something like you suggest.

For example,

```
bash$ /bin/sleep 200 &
bash$ sleep 10 && kill %1
```

**Comment by jesse-c** [comment]
That's a good solution. I'm not able to try it right now, but are you able to get the output doing it that way?

**Comment by dgryski** [comment]
I would check the contents of the `crashers` directory instead of relying on the output for the script.   You can also redirect `go-fuzz` to a file and then extract the last line or two from that.

**Comment by jesse-c** [comment]
@dgryski Ah, good point. Thanks. I'm happy to close this then unless there's support/strong use case for it.

**Comment by dvyukov** [comment]
What @dgryski said.
In a context of CI you still want an external timeout for reliability. And with that timeout there is basically no point in another timeout. It will only complicate things: what if the go-fuzz exited with non-zero status but there are no reports? or the other way around?
