### ISSUE TITLE
Max runtime for go-fuzz

### ISSUE THREAD

**Issue by JKhawaja** [dvyukov/go-fuzz#166]
Should there be a flag in the go-fuzz binary that specifies the maximum length of time go-fuzz will run for?

**Comment by dvyukov** [comment]
I don't know. Never needed it. Should there be one? Why?

**Comment by JKhawaja** [comment]
@dvyukov just seems weird to have a suite of fuzzy tests being re-run (upon a code change) taking several minutes each.

**Comment by dvyukov** [comment]
I don't understand. Please describe the full scenario.
You say "taking several minutes each". But there is no option to limit runtime. Did you implement it already outside of go-fuzz? If yes, then why do you want this in go-fuzz?
If you are talking about regression testing after each change, then potentially you want a different mode where go-fuzz just runs each input from corpus once.

**Comment by JKhawaja** [comment]
I have not implemented this outside of go-fuzz. I would like a way to automate it using go-fuzz commands only (as in a sequence of go-fuzz commands for different build-files in a makefile) to automate the creation of new corpi(?).  This would avoid manual interaction with the build process. IDK, hopefully this makes sense.

A regression mode would also be nice. But that is a slightly different topic.

**Comment by dvyukov** [comment]
Let's move the discussion to https://github.com/golang/go/issues/19109
At this point it does not make lots of sense to implement something in go-fuzz if it's not going to be upstreammed. `-fuzztime`/`-fuzzduration` was mentioned there several times.

**Comment by JKhawaja** [comment]
Oh, I did not know there was a legitimate plan in place to upstream go-fuzz (at least conceptually) to the Go project. Very cool! 😄 

Of course, this merely increases the potential bureaucratic window between my request and its fulfillment. Haha.

**Comment by dvyukov** [comment]
If there is agreement that we should do this upstream, then I do not mind accepting a pull request to go-fuzz (should be almost trivial I guess).

**Comment by JKhawaja** [comment]
>should be almost trivial

Indeed. Here is to the hope that agreements are met. 🍻   Cheers.

**Comment by nstielau** [comment]
In the "do one thing and do it well" vein, there is always `timeout` command that could be used to achieve this, with less custom code, FWIW ;)

**Comment by mmcloughlin** [comment]
> In the "do one thing and do it well" vein, there is always `timeout` command that could be used to achieve this, with less custom code, FWIW ;)

For anyone wishing to do this in CI, the following will cause it to exit with status 0 if everything goes well:

```
timeout --preserve-status --signal=INT 10s go-fuzz ...
```
