### ISSUE TITLE
Unable to open coverage profile using go tool cover with go1.9.2

### ISSUE THREAD

**Issue by pavlo-v-chernykh** [dvyukov/go-fuzz#170]
Hi Dmitry,

Thanks for a great tool.

I have faced with the next issue trying to inspect coverage profile gathered by go-fuzz.
> `go tool cover -html=coverprofile`
> `cover: inconsistent NumStmt: changed from 0 to 1`

Some go env stuff

```
GOARCH="amd64"
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GORACE=""
GOROOT="/usr/local/Cellar/go/1.9.2/libexec"
GOTOOLDIR="/usr/local/Cellar/go/1.9.2/libexec/pkg/tool/darwin_amd64"
```

go-fuzz rev: 490b850ac16b7307e047fb1ea3d91dfc5e8154f4

Snippet of cover profile that causes the issue:

```
fmt/format.go:0.0,1.1 0 0
fmt/format.go:0.0,1.1 1 0
```

There are a lot of similar lines in the cover profile with different files as well (from std lib and from a project).

I did some investigation and found the place in go tool cover sources:

https://github.com/golang/go/blob/f39050c8ebf894ccedc0b99de96f7412be97af89/src/cmd/cover/profile.go#L94-L119

Also, I think the place in `go-fuzz` that introduced that 0 statements is

https://github.com/dvyukov/go-fuzz/blob/720fd7caaeb35afbd2c9649ac860f5b3a8a4421a/go-fuzz-build/cover.go#L223

I would like to fix that issue but do not understand where is the actual problem.

**Comment by dvyukov** [comment]
Thanks for the report. I don't have time to look into this right now. Sorry.

**Comment by tiziano88** [comment]
FWIW I am also running into this issue.

**Comment by Kubuxu** [comment]
I dug a bit into it, all the results in form of `fmt/format.go:0.0,1.1` are from AST trees with Position of 0 which is NoPos (no positional information available).

Those coverage trackers are installed here:
https://github.com/dvyukov/go-fuzz/blob/master/go-fuzz-build/cover.go#L531
Although I am not sure why.

As a quick workaround `sed -i '/0.0,1.1/d' coverprofile` works.

**Comment by disconnect3d** [comment]
Hey,

an additional workaround can also be "trimming absolute paths" as listed in: https://github.com/genjidb/genji/blob/814e7f889a0200a39a3c5b1380e851e7c01a8e33/.github/workflows/test-fuzz.yaml#L101-L107

Funnily, the linked code links to @Kubuxu comment :D. 🤯
