### ISSUE TITLE
Empty GOPATH should default to "~/go"

### ISSUE THREAD

**Issue by tdewolff** [dvyukov/go-fuzz#173]
The default value for `GOPATH` when it is empty is `$HOME/go` (see https://rakyll.org/default-gopath/), but `go-fuzz-build` still gives the following error:

```
failed to execute go build: exit status 2
go: GOPATH entry is relative; must be absolute path: "".
For more details see: 'go help gopath'
```

Instead it should use the default.

**Comment by dgryski** [comment]
This will addressed by https://github.com/dvyukov/go-fuzz/issues/154
