### ISSUE TITLE
go-fuzz-build broken with golang tip

### ISSUE THREAD

**Issue by mvdan** [dvyukov/go-fuzz#186]
Using the sample png fuzzing from the README:

```
$ go version
go version devel +85dcc709a8 Tue Mar 6 11:48:37 2018 +0000 linux/amd64
$ go list .
mvdan.cc/p
$ cat f.go
package png

import (
        "bytes"
        "image/png"
)

func Fuzz(data []byte) int {
        png.Decode(bytes.NewReader(data))
        return 0
}
$ go-fuzz-build mvdan.cc/p
failed to execute go build: exit status 1
import cycle not allowed
package mvdan.cc/p/go.fuzz.main
        imports go-fuzz-dep
        imports runtime
        imports internal/bytealg
        imports go-fuzz-dep
```

Probably related to how part of runtime was split into internal/bytealg.

**Comment by mvdan** [comment]
This likely needs updating: https://github.com/dvyukov/go-fuzz/blob/1a8a6f48a772f1458d6947b93392cfea5a5d056f/go-fuzz-build/main.go#L310

**Comment by dvyukov** [comment]
@andybons you asked how upstream breaks go-fuzz.

@mvdan thanks for reporting, yes, I think we just need to update that list.

**Comment by mvdan** [comment]
Thanks for the quick fix!
