### ISSUE TITLE
Can't install go-fuzz as per README

### ISSUE THREAD

**Issue by chebizarro** [dvyukov/go-fuzz#188]
Hi there, really digging go-fuzz a lot!

I ran into the following issue several times when trying to follow the README. When running the command:

`go get -u github.com/dvyukov/go-fuzz/...
`

I get the error:

`package github.com/dvyukov/go-fuzz/slides: found packages n (crash.go) and main (gob.go) in $GOPATH/src/github.com/dvyukov/go-fuzz/slides
`

I was able to work around it by installing each package individually:

`go get -u github.com/dvyukov/go-fuzz/gen github.com/dvyukov/go-fuzz/go-fuzz-build github.com/dvyukov/go-fuzz/go-fuzz-defs github.com/dvyukov/go-fuzz/go-fuzz-dep  github.com/dvyukov/go-fuzz/go-fuzz
`

I'm pretty new to go, so I might be missing something but it seems like the slides directory is being treated as a package by the go build system.

**Comment by dvyukov** [comment]
Thanks for reporting. Should be fixed now.
