### ISSUE TITLE
Fuzzed package not instrumented

### ISSUE THREAD

**Issue by knaxo** [dvyukov/go-fuzz#196]
Is it intended that only the edges of the dependency tree are instrumented? I observed that the coverage of my fuzzing results does not include the packages I am actually fuzzing. Looking at what go-fuzz-build does, I found that not all packages copied to the tmp path are being instrumented before the binary is build. Only packages that don't have any imports are being instrumented. How can go-fuzz  know if it generates new coverage those packages? Is this a bug or am I missing something? Thanks!

**Comment by knaxo** [comment]
To check what got instrumented I am breaking here:
```
cmd := exec.Command("go", "build", "-tags", makeTags(), "-o", outf, mainPkg)
```
and check the temp directory, where the files for the build are:
```
/tmp/go-fuzz-build667403209
```
All packages at the top of the ready slice contain instrumentation. Packages which are deps to other packages (level 2..n ) are not instrumented. 

```
// only packages at the top of the tree are instrumented. 
var ready []*Package    
```

**Comment by knaxo** [comment]
You suggestion CGO=ENABLED=0 solved the issue.

**Comment by dvyukov** [comment]
CGO has known problems.
Another reason to remember https://github.com/golang/go/issues/19109

**Comment by knaxo** [comment]
Yes agree. That would be awesome and I can't understand why they haven't picked it up. Thankfully we have you to compensate for now.

**Comment by dvyukov** [comment]
I can't spend any significant time on this now unfortunately.
Please drop that note on the upstream bug. If nobody asks and reminds about this, it reasonably becomes low priority for upstream.

**Comment by josharian** [comment]
Sounds like this issue is resolved enough. I don’t see how migrating go-fuzz to Go core will fix all the issues with cgo; there’s no clear path forward at all; and there is a workaround. We could consider having go-fuzz-build fail when it encounters cgo, but that’d prevent building code that does function right now. So I’m going to go ahead and close this as unfortunate.
