### ISSUE TITLE
Compilation fails: Functions are undefined

### ISSUE THREAD

**Issue by reijin90** [dvyukov/go-fuzz#198]
Hi!

I'm not a golang pro, but I feel like I'm going crazy. I try to compile a fuzz case for a geth component. There are already some cases implemented in the code namely: `https://github.com/ethereum/go-ethereum/blob/master/core/vm/runtime/fuzz.go`. I wrote a different case with this code:
```
// +build gofuzz

package p2p

func Fuzz(data []byte) int {
        closer, rw, p, _ := testPeer(nil)
        defer closer()
        if err := Senditems(rw, &data, data); err != nil {
                return 0;
        }
        return 1
}
```
I placed the fuzz.go file in the p2p subdirectory. `testpeer` and `SendItems` are defined in the `peer_test.go` and `message.go` in the same directory (`p2p`) and package. While I can indeed compile the already added fuzz case with `~/go/bin/go-fuzz-build -tags nocgo github.com/ethereum/go-ethereum/core/vm/runtime` I can't compile with 
```
~/go/bin/go-fuzz-build -tags nocgo github.com/ethereum/go-ethereum/p2p
failed to execute go build: exit status 2
# github.com/ethereum/go-ethereum/p2p
p2p/Fuzz.go:6:22: undefined: testPeer
p2p/Fuzz.go:8:12: undefined: Senditems
```

I really don't understand how this is not working... The fuzzcase inside the geth package doesn't seem to make anything different. Please help me understand.

**Comment by reijin90** [comment]
Thanks for the hint! Judging from the output of `go build -x ` it indeed seems there are some dependencies to packages that use CGo. If I remember correctly there were some issues regarding CGo that impact Go Fuzz, right?

**Comment by dvyukov** [comment]
Right. CGO is not supported unfortunately.

**Comment by reijin90** [comment]
Hey! I found that adding `CGO_ENABLED=0` leads to a different error:
```
CGO_ENABLED=0 ~/go/bin/go-fuzz-build -tags nocgo github.com/ethereum/go-ethereum/p2p
failed to execute go build: exit status 1
go build github.com/ethereum/go-ethereum/crypto/secp256k1: build constraints exclude all Go files in /root/go/src/github.com/ethereum/go-ethereum/crypto/secp256k1
```
Seems I'll have to make some changes there to make the application not use CGO here.

**Comment by reijin90** [comment]
Ok... Removing all references to CGo didn't work...
```
root@ubuntu-s-1vcpu-1gb-fra1-01:~/go/src/github.com/ethereum/go-ethereum# CGO_ENABLED=0 ~/go/bin/go-fuzz-build -tags nocgo github.com/ethereum/go-ethereum/p2p
failed to execute go build: exit status 2
# github.com/ethereum/go-ethereum/p2p
p2p/fuzz.go:6:22: undefined: testPeer
p2p/fuzz.go:8:12: undefined: Senditems
```

Do you have an other recommendation for me to figure out what the issue is?

**Comment by dvyukov** [comment]
does this build with `CGO_ENABLED=0 go build -tags "nocgo gofuzz"`?

**Comment by reijin90** [comment]
Sadly no:
```
root@ubuntu-s-1vcpu-1gb-fra1-01:~/go/src/github.com/ethereum/go-ethereum# CGO_ENABLED=0 go build -tags "nocgo gofuzz" github.com/ethereum/go-ethereum/p2p
# github.com/ethereum/go-ethereum/p2p
p2p/fuzz.go:6:22: undefined: testPeer
p2p/fuzz.go:8:12: undefined: Senditems
```

Am I adding the right package?

**Comment by dvyukov** [comment]
Then I guess you really don't have implementation of these functions and go-fuzz-build can't possibly succeed. Probably related to nocgo tag.

**Comment by reijin90** [comment]
Do I have to mark all files that need to be added to the go-fuzz build with a `// +build gofuzz` ?

**Comment by reijin90** [comment]
> Then I guess you really don't have implementation of these functions and go-fuzz-build can't possibly succeed. Probably related to nocgo tag.

Not sure how go-fuzz can't find these files:
`https://github.com/ethereum/go-ethereum/blob/89a32451aeb418db3fd5d9c427a0c29fddb1e85b/p2p/message.go`
and 
`https://github.com/ethereum/go-ethereum/blob/89a32451aeb418db3fd5d9c427a0c29fddb1e85b/p2p/peer_test.go`

which are in the same folder as my fuzz.go, using the same package...

**Comment by dvyukov** [comment]
> Do I have to mark all files that need to be added to the go-fuzz build with a // +build gofuzz ?

See https://golang.org/pkg/go/build/#hdr-Build_Constraints

**Comment by dvyukov** [comment]
> Not sure how go-fuzz can't find these files:

It's not go-fuzz, you just said that go build fails in the same way. Nobody can find them.

**Comment by reijin90** [comment]
> > Not sure how go-fuzz can't find these files:
> 
> It's not go-fuzz, you just said that go build fails in the same way. Nobody can find them.

pardon, I don't want to blame anyone. I just don't know what the issue is... Maybe it is trivial to someone who is used to using this language. What is really confusing to me is that it works with the included fuzz.go, but not with mine eventhough I feel I have imitated everything necessary to make it work...

**Comment by reijin90** [comment]
> > Do I have to mark all files that need to be added to the go-fuzz build with a // +build gofuzz ?
> 
> See https://golang.org/pkg/go/build/#hdr-Build_Constraints

Only the fuzz.go files that are included have that build tag, just like my fuzz.go. So I guess that's not the problem either.

**Comment by reijin90** [comment]
Ok! The function testPeer is defined in a file that imports "testing" - is that some kind of pseudo package like "C" that is being ignored by go build? The golang documentation is not clear about that, it just says "It is intended to be used in concert with the “go test” command, which automates execution of any function of the form"

**Comment by reijin90** [comment]
I decided to fuzz a different function and I got it working. Really weird. I still have no idea why it's not working.

**Comment by dvyukov** [comment]
`*_test.go` files are compiled only into tests, they are not part of normal build. That's why `testPeer` is not in the package.
And `Senditems` is named `SendItems`, not `Senditems`:
https://github.com/ethereum/go-ethereum/blob/89a32451aeb418db3fd5d9c427a0c29fddb1e85b/p2p/message.go#L109
