### ISSUE TITLE
"missing verb: % at end of format str" in generated corpus

### ISSUE THREAD

**Issue by reijin90** [dvyukov/go-fuzz#199]
Hi!

I have no idea how the corpus is being created, but I noticed that one of my corpi (?) includes this line. Maybe the corpus generation code has some edge case that leads to this? If that's intended behaviour: never mind this issue.

Here is the content of the corpus:
```
  Offset: 00 01 02 03 04 05 06 07 08 09 0A 0B 0C 0D 0E 0F 	
00000000: 04 EA C0 73 65 6E 47 6D 6D 69 73 73 69 6E 67 20    .j@senGmmissing.
00000010: 76 65 72 62 3A 20 25 20 61 74 20 65 6E 64 20 6F    verb:.%.at.end.o
00000020: 66 20 66 6F 72 6D 61 74 20 73 74 72                f.format.str
```

Cheers!

**Comment by dvyukov** [comment]
This is working as intended. These inputs are random and can contain anything.
