### ISSUE TITLE
go-fuzz-build fails

### ISSUE THREAD

**Issue by andrewchambers** [dvyukov/go-fuzz#2]
Execute go-fuzz-build as the readme suggests.
```
andrew@andrew-laptop:fuzz $ go version
go version devel +ada8cdb Fri Apr 24 21:52:30 2015 +0000 linux/amd64
andrew@andrew-laptop:fuzz $ go get github.com/dvyukov/go-fuzz/...
andrew@andrew-laptop:fuzz $ go-fuzz-build github.com/dvyukov/go-fuzz/examples/png
failed to scan dir 'pkg/tool': open pkg/tool: no such file or directory
```

**Comment by dvyukov** [comment]
Do you have GOROOT set? Do you use go1.4 or tip?
I have GOROOT set and use tip.

**Comment by andrewchambers** [comment]
tip, I just updated,  no GOROOT.

**Comment by dvyukov** [comment]
what if you set GOROOT to go installation dir?

**Comment by andrewchambers** [comment]
build works with GOROOT.

**Comment by dvyukov** [comment]
Added diagnostic to go-fuzz-build, now it says:
```
GOROOT env var is not set, set it to Go installation dir
```
thanks!

**Comment by FiloSottile** [comment]
The message seems gone:

```
go-fuzz-build REDACTED
failed to execute go build: exit status 1
../../../REDACTED: cannot find package "bufio" in any of:
	/usr/local/src/bufio (from $GOROOT)
```

**Comment by dvyukov** [comment]
@FiloSottile  can you provide a reproducer?
Have you checkout the latest version of go-fuzz? I've fixed an issue that could lead to the error you see some time ago.

**Comment by dvyukov** [comment]
@FiloSottile and yes, the GOROOT is now inferred from go command location. In your case it is inferred to be /usr/local.

**Comment by FiloSottile** [comment]
Ah, then there's the problem; the go binary can be stored or linked wherever. I'll make a PR.
