### ISSUE TITLE
libFuzzer support

### ISSUE THREAD

**Issue by guidovranken** [dvyukov/go-fuzz#213]
Let's continue here.

This is what I have now: https://github.com/guidovranken/go-fuzz/tree/libfuzzer-mode

```sh
clang -fsanitize=fuzzer-no-link -c $GOPATH/src/github.com/dvyukov/go-fuzz/C/main_libFuzzer_extra_counters.c
go build github.com/dvyukov/go-fuzz/go-fuzz-build
./go-fuzz-build -libfuzzer <pkg>
clang++ -fsanitize=fuzzer main_libFuzzer_extra_counters.o <generated archive.a> -o fuzzer
```

I retained the original functionality in ```go-fuzz-build/main.go```, but removed what wasn't needed in ```go-fuzz-deps/main.go``` for now. Maybe we can have a ```go-fuzz-deps-libFuzzer``` directory for when ```-libfuzzer``` is specified?

**Comment by dvyukov** [comment]
This is what I should be looking at, right?
https://github.com/guidovranken/go-fuzz/commit/5b859d76c166a50624386b575bdcfb074ac278c4

**Comment by dvyukov** [comment]
I've created a pull request for this for discussion purposes:
https://github.com/dvyukov/go-fuzz/pull/217

**Comment by reijin90** [comment]
If you don't mind me asking, what is your rationale behind adding this? Do you expect different behaviour? Better performance? Future CGo compatibility?

**Comment by guidovranken** [comment]
> If you don't mind me asking, what is your rationale behind adding this? Do you expect different behaviour? Better performance? Future CGo compatibility?

Being able to integrate into oss-fuzz which does not support the built-in gofuzz engine.

Also being able to do differential fuzzing against software written in other languages, like https://github.com/guidovranken/bignum-fuzzer (which incorporates Golang code but currently without instrumentation).

**Comment by josharian** [comment]
-libfuzzer support is in.
