### ISSUE TITLE
libfuzzer darwin support

### ISSUE THREAD

**Issue by dgryski** [dvyukov/go-fuzz#222]
Currently libfuzzer support is only enabled on Linux.  What work is required to make this work on Darwin too?

https://github.com/dvyukov/go-fuzz/commit/897eea5ebefe1f86cce89d447bf177cba6e3d451#diff-9e13bfa7148874b4e09bfc5d2c8163daR643

**Comment by josharian** [comment]
Looks to me like upstream libFuzzer only works on Linux. So this is in clang’s court.

**Comment by dgryski** [comment]
I've used libfuzzer successfully on my Mac.  Maybe the comment is incorrect?

**Comment by josharian** [comment]
http://llvm.org/docs/doxygen/FuzzerExtraCounters_8cpp_source.html

**Comment by dgryski** [comment]
Ah, the extra counters.  Ok, blocked on upstream then.

**Comment by josharian** [comment]
There’s nothing for us to do here for now. If upstream adds Darwin support, we can re-open.
