### ISSUE TITLE
libFuzzer support may have broken or at least altered Windows support

### ISSUE THREAD

**Issue by thepudds** [dvyukov/go-fuzz#224]
I am not sure if this is 1 issue or 2 issues, or perhaps user error, but it seems `go-fuzz-build` now fails with error `build output ... already exists and is not an object file` on Windows.

These steps currently fail on Windows with the latest version of dvyukov/go-fuzz:
```
set CGO_ENABLED=0
set GOPATH=C:\temp\gopath-go-fuzz-master
set PATH=%GOPATH%\bin;%PATH%
go get -u github.com/dvyukov/go-fuzz/...
go get -v -d github.com/dvyukov/go-fuzz-corpus/png
cd %GOPATH%/src/github.com/dvyukov/go-fuzz-corpus
cd png
go-fuzz-build
```
`go-fuzz-build` fails with error:
```
failed to execute go build: exit status 1
go build github.com/dvyukov/go-fuzz-corpus/png/go.fuzz.main: 
 build output "C:\\Users\\...\\AppData\\Local\\Temp\\go-fuzz863067130"
 already exists and is not an object file
```

If you do the same steps but without `set CGO_ENABLED=0`, it instead fails with:

```
could not load standard library: go [list -e -json -compiled -test=false -export=false -deps=false -find=true -- std]: exit status 2: # runtime/cgo
exec: "gcc": executable file not found in %PATH%
```

I suspect CGO_ENABLED / gcc issue might be a separate issue from `build output ... already exists and is not an object file` issue.

The 2019-03-04 version at commit b73ac4d3ed from just before the libFuzzer work seems to function properly on Windows (here still setting CGO_ENABLED=0 to avoid complaints about gcc):

```
set CGO_ENABLED=0
set GOPATH=C:\temp\gopath-go-fuzz-2019-03-04-b73ac4d3ed
set PATH=%GOPATH%\bin;%PATH%
go get -u github.com/dvyukov/go-fuzz/...
go get -v -d github.com/dvyukov/go-fuzz-corpus/png
cd %GOPATH%/src/github.com/dvyukov/go-fuzz
git checkout b73ac4d3ed
go install ./...
cd %GOPATH%/src/github.com/dvyukov/go-fuzz-corpus
cd png
go-fuzz-build
go-fuzz
```

<pre>
$ go version
go version go1.12 windows/amd64
</pre>

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env

set GOARCH=amd64
set GOBIN=
set GOCACHE=C:\...\AppData\Local\go-build
set GOEXE=.exe
set GOFLAGS=
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GOOS=windows
set GOPATH=C:\temp\gopath-go-fuzz-master
set GOPROXY=
set GORACE=
set GOROOT=C:\Go
set GOTMPDIR=
set GOTOOLDIR=C:\Go\pkg\tool\windows_amd64
set GCCGO=gccgo
set CC=gcc
set CXX=g++
set CGO_ENABLED=0
set GOMOD=
set CGO_CFLAGS=-g -O2
set CGO_CPPFLAGS=
set CGO_CXXFLAGS=-g -O2
set CGO_FFLAGS=-g -O2
set CGO_LDFLAGS=-g -O2
set PKG_CONFIG=pkg-config
set GOGCCFLAGS=-m64 -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=C:\...\Temp\go-build648862030=/tmp/go-build -gno-record-gcc-switches

</pre></details>

CC @josharian

**Comment by josharian** [comment]
Windows doesn't like calls to os.Rename to overwrite an existing file. We work around this elsewhere in go-fuzz-build. I will take a look, probably sometime late next week. Could be the libfuzzer change, or I may have broken this in my follow-up to the libfuzzer change. You could also take a look if you want. The fix is likely to be simple, once you track it down.
