### ISSUE TITLE
Frequent restarts

### ISSUE THREAD

**Issue by weissjeffm** [dvyukov/go-fuzz#23]
My output looks like this:

```
[jweiss@localhost fuzz]$ go-fuzz -bin=./fuzz-fuzz -corpus=corpus -workdir=./work
2015/05/26 06:50:47 slaves: 8, corpus: 3 (1s ago), crashers: 1, restarts: 1/0, execs: 0 (0/sec), cover: 0.00%, uptime: 3s
2015/05/26 06:50:50 slaves: 8, corpus: 3 (4s ago), crashers: 1, restarts: 1/0, execs: 0 (0/sec), cover: 2.88%, uptime: 6s
2015/05/26 06:50:53 slaves: 8, corpus: 3 (7s ago), crashers: 1, restarts: 1/2, execs: 3762 (418/sec), cover: 2.88%, uptime: 9s
2015/05/26 06:50:56 slaves: 8, corpus: 7 (0s ago), crashers: 1, restarts: 1/1, execs: 5824 (485/sec), cover: 2.88%, uptime: 12s
2015/05/26 06:50:59 slaves: 8, corpus: 8 (2s ago), crashers: 1, restarts: 1/1, execs: 7867 (524/sec), cover: 3.01%, uptime: 15s
2015/05/26 06:51:02 slaves: 8, corpus: 8 (5s ago), crashers: 1, restarts: 1/1, execs: 13276 (738/sec), cover: 3.03%, uptime: 18s
2015/05/26 06:51:05 slaves: 8, corpus: 8 (8s ago), crashers: 1, restarts: 1/2, execs: 17609 (838/sec), cover: 3.03%, uptime: 21s
2015/05/26 06:51:08 slaves: 8, corpus: 8 (11s ago), crashers: 1, restarts: 1/2, execs: 20109 (838/sec), cover: 3.03%, uptime: 24s
2015/05/26 06:51:11 slaves: 8, corpus: 8 (14s ago), crashers: 1, restarts: 1/2, execs: 23696 (878/sec), cover: 3.03%, uptime: 27s
2015/05/26 06:51:14 slaves: 8, corpus: 8 (17s ago), crashers: 1, restarts: 1/2, execs: 28550 (952/sec), cover: 3.03%, uptime: 30s
2015/05/26 06:51:17 slaves: 8, corpus: 8 (20s ago), crashers: 1, restarts: 1/2, execs: 31179 (945/sec), cover: 3.03%, uptime: 33s
2015/05/26 06:51:20 slaves: 8, corpus: 8 (23s ago), crashers: 1, restarts: 1/3, execs: 32948 (915/sec), cover: 3.03%, uptime: 36s
2015/05/26 06:51:23 slaves: 8, corpus: 8 (26s ago), crashers: 1, restarts: 1/3, execs: 35817 (918/sec), cover: 3.03%, uptime: 39s
2015/05/26 06:51:26 slaves: 8, corpus: 8 (29s ago), crashers: 1, restarts: 1/3, execs: 38258 (911/sec), cover: 3.03%, uptime: 42s
2015/05/26 06:51:29 slaves: 8, corpus: 8 (32s ago), crashers: 1, restarts: 1/3, execs: 40804 (907/sec), cover: 3.03%, uptime: 45s
2015/05/26 06:51:32 slaves: 8, corpus: 8 (35s ago), crashers: 1, restarts: 1/3, execs: 43294 (902/sec), cover: 3.03%, uptime: 48s
2015/05/26 06:51:35 slaves: 8, corpus: 8 (38s ago), crashers: 1, restarts: 1/4, execs: 45034 (883/sec), cover: 3.03%, uptime: 51s
2015/05/26 06:51:38 slaves: 8, corpus: 8 (41s ago), crashers: 1, restarts: 1/4, execs: 45192 (837/sec), cover: 3.03%, uptime: 54s
2015/05/26 06:51:41 slaves: 8, corpus: 8 (44s ago), crashers: 1, restarts: 1/4, execs: 45317 (795/sec), cover: 3.03%, uptime: 57s
2015/05/26 06:51:44 slaves: 8, corpus: 8 (47s ago), crashers: 1, restarts: 1/4, execs: 45960 (766/sec), cover: 3.03%, uptime: 1m0s
2015/05/26 06:51:47 slaves: 8, corpus: 8 (50s ago), crashers: 1, restarts: 1/4, execs: 46377 (736/sec), cover: 3.03%, uptime: 1m3s
2015/05/26 06:51:50 slaves: 8, corpus: 8 (53s ago), crashers: 1, restarts: 1/4, execs: 46663 (707/sec), cover: 3.03%, uptime: 1m6s
```

The slowness is an obvious problem, but what I don't understand is why it is restarting so frequently. Only one input caused a crash, so why does it have to restart every 4 executions?  As the test goes on, the ratio improves but not much (after 20 minutes it's 1/53). If I look at my process list over time, each one seems to live for about 5-10 seconds.

I don't know where I can get more debugging information. I can't print anything to stdout because it's not captured anywhere. Can the reason for restart be output somewhere?

One thing that would be "nice to have" is a distribution of "interestingness" scores,eg:

`interestingness: 0: 1207, 1: 75, 2: 12`

Also I notice there is a "work/suppressions" directory that is not described in the README. What is that? Seems like some stdout goes there but not sure what makes it there and what doesn't.

Finally, the corpus increases to 8 after two seconds, and 20 minutes later, it's the exact same 8 items in the corpus. Is that normal?

**Comment by dvyukov** [comment]
Suppressions is some extract of the crash report that characterizes the crash (but without variadic information like exact pointer values). If go-fuzz sees a new crash that lead to the same suppression, it discards the crash as duplicate.
What happens in your case, I think, is that the discovered crash happens really very frequently. But it is deduplicated by the suppressions mechanism. Thus the frequent restarts. Fix the crasher.

**Comment by dvyukov** [comment]
> interestingness: 0: 1207, 1: 75, 2: 12

please elaborate
interestingness of what? and measured in what?

**Comment by weissjeffm** [comment]
Ok so even though there's 1 crasher it happens nearly every time. Makes sense now.

The interestingness score is what's returned from the Fuzz function. In my particular Fuzz function the score can range from 0-5. Would be nice to know, for example, what percentage of the executions are scoring zero versus higher scores.

I'm not even sure what the tool *does* with the score, that doesn't seem to be described anywhere. Is it better to have lots of granular scores or is 0,1,2 good enough?

**Comment by dvyukov** [comment]
@weissjeffm Does fixing the crash resolves the issue with restarts?

Yes, go-fuzz internal state is quite un-transparent at the moment. Dumping all possible information to console all the time is not an option. I would like go-fuzz to serve a status page over HTTP. Then that page could contain all kinds of information with maximum detalization. But I don't have time for this right now. If you are really curious, you can add some print statement locally.

> Is it better to have lots of granular scores or is 0,1,2 good enough?

Currently go-fuzz distinguishes only 0, 1 and >=2. 1 and >=2 inputs receive priority boost (chosen for mutations more frequently). So lots of granularity does not make sense at the moment. And I am leaning towards even simpler scheme: correct/incorrect (true, false).

**Comment by weissjeffm** [comment]
> you can add some print statement locally.

You're referring to adding print's inside the go-fuzz source, right?

> Currently go-fuzz distinguishes only 0, 1 and >=2

Ok, the docs are not that clear here, since it says that scheme is "suggested" but actually there is no other choice.

**Comment by dvyukov** [comment]
> You're referring to adding print's inside the go-fuzz source, right?

yes

> Ok, the docs are not that clear here, since it says that scheme is "suggested" but actually there is no other choice.

Agree. I don't make my mind yet.

**Comment by weissjeffm** [comment]
Sorry to keep using this issue to ask questions, but 

```
2015/06/04 15:54:39 slaves: 24, corpus: 795 (9h15m ago), crashers: 0, restarts: 1/10000, execs: 14872952770 (55521/sec), cover: 2.84%, uptime: 74h24m
```

There have been no new corpus items in 9 hours, and only 2 new ones found in the last 24 hours. Should I let it continue or is it basically done?

How can I know when to stop? AFL docs say to let it run at least one round, but I have no idea how I would see when that occurs in go-fuzz.

**Comment by dvyukov** [comment]
I don't have a definitely answer. Probability of finding anything interesting exponentially decreases over time. There are chances that it won't find anything interesting in the next 1000 hours as well. And there are chances it will discover a new input that examines whole new subsystem in the program (that was not examined previously) in the next second. It also depends on the code complexity and input complexity -- more complex code and inputs require more time. 
You decide.
