### ISSUE TITLE
Two bugs in russross/blackfriday

### ISSUE THREAD

**Issue by opennota** [dvyukov/go-fuzz#25]
https://github.com/russross/blackfriday/issues/172
https://github.com/russross/blackfriday/issues/173

**Comment by dvyukov** [comment]
Nice! Especially taking into account "It is paranoid about its input (so you can safely feed it user-supplied data)...". Added to Trophies section:
https://github.com/dvyukov/go-fuzz/blob/master/README.md
Thanks for letting me know!
