### ISSUE TITLE
go-fuzz doe not start executing

### ISSUE THREAD

**Issue by klauspost** [dvyukov/go-fuzz#250]
Today one of fuzz tests started randomly to not execute:
```
e:\gopath\src\github.com\klauspost\compress-fuzz\flate>go-fuzz -bin=fuzz-build.zip -workdir=flate -procs=4
2019/06/12 20:25:16 workers: 4, corpus: 406 (3s ago), crashers: 0, restarts: 1/0, execs: 0 (0/sec), cover: 0, uptime: 3s
2019/06/12 20:25:19 workers: 4, corpus: 406 (6s ago), crashers: 0, restarts: 1/0, execs: 0 (0/sec), cover: 1208, uptime: 6s
2019/06/12 20:25:22 workers: 4, corpus: 406 (9s ago), crashers: 0, restarts: 1/0, execs: 0 (0/sec), cover: 1208, uptime: 9s
2019/06/12 20:25:25 workers: 4, corpus: 406 (12s ago), crashers: 0, restarts: 1/0, execs: 0 (0/sec), cover: 1208, uptime: 12s
....
2019/06/12 20:28:04 workers: 4, corpus: 406 (2m51s ago), crashers: 0, restarts: 1/0, execs: 0 (0/sec), cover: 1208, uptime: 2m51s
2019/06/12 20:28:07 workers: 4, corpus: 406 (2m54s ago), crashers: 0, restarts: 1/0, execs: 0 (0/sec), cover: 1208, uptime: 2m54s
2019/06/12 20:28:10 workers: 4, corpus: 406 (2m57s ago), crashers: 0, restarts: 1/0, execs: 0 (0/sec), cover: 1208, uptime: 2m57s
...
```

The fuzz test is basically just a lightly modified version of your [flate test](https://github.com/klauspost/compress-fuzz/blob/master/flate/flate.go). But even if there was a problem it should still execute?

Using latest master of go-fuzz. Go v1.12.1  (obviously not updated in a while)

What could be a reason for this? I have disabled AV on my system. The really weird thing is that 1 in 10 times it will start correctly.

**Comment by josharian** [comment]
Anything notable if you pass `-v=4` to go-fuzz?

**Comment by dvyukov** [comment]
Please try with `CGO_ENABLED=0`. That was the most common reason for such behavior.

**Comment by klauspost** [comment]
It has not happened for a while. Closing until I have something more concrete.
