### ISSUE TITLE
Question: Best way to handle multiple tests

### ISSUE THREAD

**Issue by howardjohn** [dvyukov/go-fuzz#251]
I am trying to fuzz many (30+) different protobuffs. Each one has the same testing, the only difference being what struct they are serialized into. I see there is ongoing work in https://github.com/dvyukov/go-fuzz/issues/230 to support multiple fuzz functions, but in the meantime I was wondering if there was a preferred way to do this kind of testing. Some ideas I had:

* At start of test, pick a random proto to use. I think this may cause issues though since its not deterministic?
* Test ALL of them in one function, and return 1 if any of them produce a valid struct.
* Store a list of all types, and read the first byte and use that to determine the index into the type list for which to use.

Is there any benefits to one of these approaches that would make go-fuzz handle them better than the others?

I know I can just do them all separately but its a lot of operational burden to run the test 30 times rather than just run one command and have it run overnight

**Comment by josharian** [comment]
> At start of test, pick a random proto to use. I think this may cause issues though since it's not deterministic?

Correct. I would recommend against this.

> Test ALL of them in one function, and return 1 if any of them produce a valid struct.

This is a viable approach. The sample tests in go-fuzz-corpus also do this. Note that returning +1 is a relatively weak signal, so you don't need to worry that it will screw anything up too much. This approach may be preferable if many of your protobufs share common structure.

> Store a list of all types, and read the first byte and use that to determine the index into the type list for which to use.

This is also a viable approach, but in my experience, it makes the fuzz function more annoying to write.

> I know I can just do them all separately but its a lot of operational burden to run the test 30 times rather than just run one command and have it run overnight

I know you know this, but doing them separately remains the best option for now. What I have done in the past for things like this is to set up a little bash loop, and use `timeout` (or `gtimeout` if installed via homebrew) to run each in turn for a fixed amount of time. Then let that run overnight. If you do this, be sure to not set the per-fuzz timeout too short. The initial phase of fuzzing is just to read in and re-minimize the existing corpus, which can take a few minutes; during that time, no new fuzzing is occurring.

**Comment by howardjohn** [comment]
Thanks! very useful info
