### ISSUE TITLE
Question/Discussion: libFuzzer backTrace and integration

### ISSUE THREAD

**Issue by yevgenypats** [dvyukov/go-fuzz#254]
The libFuzzer integration works pretty smooth though the backtrace is much less clear then the equivalent go-fuzz vanilla engine. Is there a theoretical possibility that libFuzzer will be able to output a better stack trace?

The integration to libFuzzer imho is important and also can save some time for example implementing same logic again in go-fuzz like distributed fuzzing, timeouts, etc... and only focus on the go compilation. instrumentation and integration part.

I didn't deep dive into the go-fuzz core source so I don't really know if this idea is possible or makes sense. Will be happy to hear feedback.

EDIT: I saw something similar implemented in rust [fuzzer](https://rust-fuzz.github.io/book/cargo-fuzz/tutorial.html) using a flag `RUST_BACKTRACE=1` though I don't know specifically how they implemented it yet.

CC @dvyukov

**Comment by dvyukov** [comment]
Looking at your example output here:
https://github.com/fuzzitdev/example-go

This is a perfect Go backtrace, with line numbers and even argument values (so even better than one can get for C/C++):
```
panic: runtime error: index out of range

goroutine 17 [running, locked to thread]:
github.com/fuzzitdev/example-go/pkg/parser.ParseComplex.func5(...)
        /go/src/github.com/fuzzitdev/example-go/pkg/parser/parse_complex.go:5
github.com/fuzzitdev/example-go/pkg/parser.ParseComplex(0x2aabb20, 0x5, 0x5, 0xc00001e040)
        /go/src/github.com/fuzzitdev/example-go/pkg/parser/parse_complex.go:5 +0x1b2
github.com/fuzzitdev/example-go/pkg/parser.Fuzz(...)
        /go/src/github.com/fuzzitdev/example-go/pkg/parser/parse_complex_fuzz.go:6
main.LLVMFuzzerTestOneInput(0x2aabb20, 0x5, 0x545b78)
        /tmp/go-fuzz-build316206684/gopath/src/github.com/fuzzitdev/example-go/pkg/parser/go.fuzz.main/main.go:35 +0x84
```


We could not print this part, which is useless:
```
==4262== ERROR: libFuzzer: deadly signal
    #0 0x45c110 in __sanitizer_print_stack_trace (/go/src/github.com/fuzzitdev/example-go/parser-fuzz.libfuzzer+0x45c110)
    #1 0x43b79b in fuzzer::PrintStackTrace() (/go/src/github.com/fuzzitdev/example-go/parser-fuzz.libfuzzer+0x43b79b)
    #2 0x422123 in fuzzer::Fuzzer::CrashCallback() (/go/src/github.com/fuzzitdev/example-go/parser-fuzz.libfuzzer+0x422123)
    #3 0x7f0ba60ff72f  (/lib/x86_64-linux-gnu/libpthread.so.0+0x1272f)
    #4 0x4acc70 in runtime.raise /tmp/go-fuzz-build316206684/goroot/src/runtime/sys_linux_amd64.s:149
```

I see libfuzzer has some options for this:
```
  if (Options.HandleBus)
    SetSigaction(SIGBUS, CrashHandler);
  if (Options.HandleAbrt)
    SetSigaction(SIGABRT, CrashHandler);
```

There is also something called __sanitizer_acquire_crash_state in libfuzzer:
```
void Fuzzer::CrashCallback() {
  if (EF->__sanitizer_acquire_crash_state &&
      !EF->__sanitizer_acquire_crash_state())
    return;
```
Perhaps we could define this __sanitizer_acquire_crash_state in the go-fuzz glue to suppress all libfuzzer crash reports.

**Comment by yevgenypats** [comment]
Got it, Thanks. It is indeed a perfect Go backtrace, I might looked at another backtrace and mixed something up. I'll look into the glue part as well, to see If I can eliminate the useless part as you suggested.

**Comment by dvyukov** [comment]
> I'll look into the glue part as well, to see If I can eliminate the useless part as you suggested.

Potentially an easier solution is to add some libfuzzer flag that will prevent it from setting the signal handler. There seems to be one. But I don't know the exact name.
