### ISSUE TITLE
Can I rely on sonar mechanism to avoid inconsistent checksum?

### ISSUE THREAD

**Issue by Cipher731** [dvyukov/go-fuzz#256]
Since the sonar mechanism seems to aim at problems like wrong checksum. Is it reliable enough to 
get me rid of mannually adding checksum? If not, what kind of effects can I expect from it?

**Comment by josharian** [comment]
Relying on sonar might work, eventually, but it'll be really slow, compared to generating a correct checksum yourself. And one of the main challenges of fuzzing is to make good use of your CPU cycles. (As a trivial observation, you could just send in entirely random data. That will eventually find any bug that fuzzing would, just much, much slower.)

Hope that helps. I'll close this for now, pending further input.

**Comment by Cipher731** [comment]
Thank you for reply, @jeffallen . 
Is the slowness you mentioned caused by the fact that only 1/1000 interations goes to sonar?
By the way, I wonder if there is more detailed documentation about the inside mechanisms or just the comments and source code? I learned the idea about sonar only via /slides/go-fuzz.slide. But it turned out that my understanding is too shallow :(

**Comment by josharian** [comment]
Partially it is that only a small fraction goes to sonar. But also sonar isn’t super sophisticated: It can only do fairly obvious replacements in the input (which means it can fail entirely), and it has to do all of them (more slowness).

I don’t know of other good docs, no. There’s a nice afl design doc that helps a bit. But mostly it is reading the code. (That’s how I learned about it myself, and my understanding is not complete.) Or you can ask Dmitry. :)

**Comment by dvyukov** [comment]
@Cipher731 the simplest thing to do: put a panic after the checksum check and see if it fires. Yes - sonar works, not - it doesn't. If you provide a self-contained test where sonar fails, but could work, adding it to https://github.com/dvyukov/go-fuzz/blob/master/test/test.go would be useful. All such "false negative" cases can only be discovered only by somebody manually looking into some particular case.
