### ISSUE TITLE
go-fuzz-build: add "do not instrument" flag

### ISSUE THREAD

**Issue by josharian** [dvyukov/go-fuzz#266]
I would like to add a flag to request that go-fuzz-build omit instrumentation for a set of packages. Possible ui:

```
  -preserve string
    	a space-separated list of import paths not to instrument during the build
```

Use cases:

* Omit areas of code that are uninteresting but pollute coverage.
* Provide a workaround for instrumentation bugs.

I'm happy to implement. (It's easy.) First, though: opinions? concerns? bikesheds? (I don't love `-preserve`, but it's the shortest clear thing I could think of.)

cc @thepudds @dvyukov @mvdan

**Comment by josharian** [comment]
Actually, I'd like to have preserve accept a comma-separated list of import paths, not space separated. Or if the divergence from `-tags` is too great, then accept both.

**Comment by dvyukov** [comment]
My only concern is what happens when/if we upstream go-fuzz: do we keep this? Or dropping?
If keeping, then we need to note this in the proposal.

**Comment by josharian** [comment]
I don't know whether we'd want to keep it. I guess the default would be to not keep it and see how many people complain about its newfound absence, thereby learning about its utility to people other than me.

**Comment by dvyukov** [comment]
OK I don't mind shoving it into go-fuzz in this status.
