### ISSUE TITLE
Created go-fuzz*.exe in /tmp after go-fuzz run

### ISSUE THREAD

**Issue by alexlyp** [dvyukov/go-fuzz#28]
I noticed 2 go-fuzz*.exe are created and left in /tmp after every run of go-fuzz.  The other tmp files that are created are cleaned up correctly.

Running on linux/amd64

**Comment by alexlyp** [comment]
Working fix in #30

**Comment by dvyukov** [comment]
Thanks for reporting this.
Fixed in c791e347cb25664dff7a215e51f1d6f65563458a
Some temp files were also left after go-fuzz-build.
Tested that there are no temp files after go-fuzz-build, go-fuzz, ^C, go-fuzz, ^C.
