### ISSUE TITLE
how to only run corpus (e.g. for CI)?

### ISSUE THREAD

**Issue by TimSatke** [dvyukov/go-fuzz#289]
I would like to use my corpus as regression tests in my continuous integration pipeline. However, I cannot find any documentation on how to only run the corpus, also, the command line help doesn't help me a lot (or I just overlooked it).
Can you help me?

**Comment by dvyukov** [comment]
There is nothing automatic for this.
It's part of the upstream fuzzing support proposal, namely, merely running go test should do it.

**Comment by TimSatke** [comment]
Good point. Is there an issue we can link this to, so that this can be closed? (Also, if not, feel free to close this).

**Comment by thepudds** [comment]
@TimSatke the canonical issue is https://golang.org/issue/19109. 

You can read the proposed listed there. 

Also, if interested, https://github.com/thepudds/fzgo is a prototype of that proposal, and it currently includes the ability to run the corpus as a test (without actually fuzzing to generate new imputs).

**Comment by TimSatke** [comment]
Thank you so much for the quick response!

**Comment by thepudds** [comment]
Sorry for double post, but from the fzgo README:

> * The corpus is automatically used as deterministic input to unit tests when running a normal go test.
> * Individual corpus files can be unit tested via fzgo test -fuzz=. -run=TestCorpus/<name>.
