### ISSUE TITLE
Could not import C (no metadata for C)

### ISSUE THREAD

**Issue by MariusVanDerWijden** [dvyukov/go-fuzz#291]
Hey, I'm currently trying to fuzz a library that was generated from rust and run into an `Could not import C (no metadata for C) error`.

I found these prs to golang: https://go-review.googlesource.com/c/tools/+/214738/ https://go-review.googlesource.com/c/tools/+/214943/
The second one was merged into master (but not included in the latest release). I also tried to apply the first one, however this gives me multiple `undeclared name: C` errors.

 The library is here: https://github.com/shamatar/eip2537rustwrapper
Repro: 

- clone the library, 
- execute the functions in their readme
- edit package from main -> bls
- add `func Fuzz(data []byte) int { return 1 }`
- run go-fuzz-build

**Comment by josharian** [comment]
Thanks for the issue. That's unfortunate. Sounds like more of a go/packages problem than a go-fuzz problem (except insofar we inherent their problems). I don't have the bandwidth to dig into this now, so I'm afraid I'm inclined to wait a bit and see whether the situation improves upstream. You might want to check out the new llvm fuzz support added to the toolchain and see whether you can use that.

**Comment by MariusVanDerWijden** [comment]
Yep sure, will do!
