### ISSUE TITLE
How to reproduce crash in go-fuzz

### ISSUE THREAD

**Issue by lipeng28** [dvyukov/go-fuzz#302]
Hi There

Currently go-fuzz is able to produce a bunch of crashes, I am wondering how go-fuzz is able to reproduce crashes easier. What I can think about is to create another test driver with the same code body as Fuzz function, then build it to replay the crash seed. 

Thanks
Peng

**Comment by dvyukov** [comment]
Hi Peng,

Here is what I use:
https://github.com/google/syzkaller/blob/master/pkg/report/report_test.go#L383-L396
Roughly what you described, but without duplicating Fuzz function code and also serves as a regression test.
