### ISSUE TITLE
Documentation suggestion: []byte -> structured data

### ISSUE THREAD

**Issue by lavalamp** [dvyukov/go-fuzz#304]
You can use go-fuzz to fuzz arbitrary go structures via this adapter: https://godoc.org/github.com/google/gofuzz#NewFromGoFuzz

Maybe worth mentioning somewhere?

**Comment by dvyukov** [comment]
Interesting. Have not seen this support before.
Worth mentioning.
I would say as a section right in the main README.md, that's how the current docs seem to be organized.

**Comment by lavalamp** [comment]
Some good details [here](https://github.com/golang/go/issues/19109#issuecomment-702484259), maybe I should improve this a bit before advertising 😅

**Comment by lavalamp** [comment]
If I have another time slice to make sure this makes sense, I'll come back with a documentation PR. But I don't think this issue needs to stay open until then :)
