### ISSUE TITLE
The Diff About cover.exe and sonar.exe

### ISSUE THREAD

**Issue by DuckRui** [dvyukov/go-fuzz#344]
Hi, I am reading about the go-fuzz source code, But I'm not understand the different about cover.exe and sonar.exe. It seems like both of them are used to calculate coverage. Can you help me solve this problem? Thank you very much!

**Comment by dvyukov** [comment]
IIRC cover.exe contains instrumentation that allows to collect code coverage; while sonar.exe contains instrumentation that allows to collect comparison operands.
