### ISSUE TITLE
abi_arm64.h: no such file or directory

### ISSUE THREAD

**Issue by hoangong** [dvyukov/go-fuzz#348]
I have this error when running go-fuzz-build
```
go-fuzz-build
failed to execute go build: exit status 1
# runtime
/var/folders/nl/q5qsnt0d6fvd0bjfdb54h04w0000gp/T/go-fuzz-build1901158247/goroot/src/runtime/rt0_darwin_arm64.s:7: #include: open /var/folders/nl/q5qsnt0d6fvd0bjfdb54h04w0000gp/T/go-fuzz-build1901158247/goroot/pkg/include/cgo/abi_arm64.h: no such file or directory
```

go version:
```
go version
go version go1.20.6 darwin/arm64
```

I don't see this error when running go AMD version.

**Comment by shareef-dweikat** [comment]
Same issue here

**Comment by an-oo-na** [comment]
Same question. Has anyone solved it? T-T

**Comment by thepudds** [comment]
Hi there, I can take a look at this. There's a decent chance it might be a small fix.

If a large fix is needed, probably unlikely to happen. In general, people are encouraged to use the [native fuzzing support in 'go test'](https://go.dev/security/fuzz/). See for example Dmitry's comment in https://github.com/dvyukov/go-fuzz/issues/329#issuecomment-1589823351.
