### ISSUE TITLE
Encountering Error When Using go-fuzz-build

### ISSUE THREAD

**Issue by jlguochn** [dvyukov/go-fuzz#351]
When I use go-fuzz-build ., I encounter the error 'go/pkg/mod/github.com/iden3/go-iden3-crypto@v0.0.15/ffg/element_fuzz.go:103:7: b declared and not used typechecking of . failed'.

**Comment by josharian** [comment]
Workaround: add `_ = b` after it.

**Comment by jlguochn** [comment]
> Workaround: add `_ = b` after it.

thanks, it's work.
