### ISSUE TITLE
Can't build with go-fuzz-build, import cycle not allowed

### ISSUE THREAD

**Issue by Thomasdezeeuw** [dvyukov/go-fuzz#40]
I ran `go-fuzz-build github.com/dvyukov/go-fuzz/examples/png`, and I got this error:

```
failed to execute go build: exit status 1
import cycle not allowed
package go-fuzz-main
        imports github.com/dvyukov/go-fuzz/examples/png
        imports bytes
        imports github.com/dvyukov/go-fuzz/go-fuzz-dep
        imports time
        imports internal/syscall/windows/registry
        imports github.com/dvyukov/go-fuzz/go-fuzz-dep
```

I get the same error trying to run it on my own code. I'm running Windows 7 64bit, go compiled from source at commit `aadd84e0c4ac2476644d0f60b4873867c9549306`, just after 1.5 beta 2.

**Comment by Thomasdezeeuw** [comment]
I've tried this on Ubuntu 14.04 64 bit (virtualized on win7 64bit with Virtual box) and it works. So it seems like a Windows specific issue.

**Comment by dvyukov** [comment]
Hi,

6ac550c should fix the bug.
I don't have a windows machine at the moment. Please test whether it actually fixed the bug.

**Comment by Thomasdezeeuw** [comment]
That fixed it, thank you.
