### ISSUE TITLE
panic with new key-value logic

### ISSUE THREAD

**Issue by dgryski** [dvyukov/go-fuzz#42]
I received the following panic with go-fuzz a60c04bd38158403027a022ce604eed9cbe74d60
while fuzzing github.com/Sereal/Sereal/Go/sereal.

Looks like the new key-value stuff that was just merged.

```
panic: runtime error: slice bounds out of range

goroutine 50 [running]:
github.com/dvyukov/go-fuzz/go-fuzz/versifier.structureKeyValue(0xc82027bb00, 0x6, 0x8, 0x0, 0x0, 0x0)
        /home/dgryski/work/src/gocode/src/github.com/dvyukov/go-fuzz/go-fuzz/versifier/versifier.go:696 +0x75e
github.com/dvyukov/go-fuzz/go-fuzz/versifier.structure(0xc82027bb00, 0x6, 0x8, 0x0, 0x0, 0x0)
        /home/dgryski/work/src/gocode/src/github.com/dvyukov/go-fuzz/go-fuzz/versifier/versifier.go:575 +0xdd
github.com/dvyukov/go-fuzz/go-fuzz/versifier.BuildVerse(0x0, 0xc8202e0330, 0xf, 0x2b, 0x10000)
        /home/dgryski/work/src/gocode/src/github.com/dvyukov/go-fuzz/go-fuzz/versifier/versifier.go:55 +0x1b9
main.(*Hub).loop(0xc820200e00)
        /home/dgryski/work/src/gocode/src/github.com/dvyukov/go-fuzz/go-fuzz/hub.go:225 +0x19ed
created by main.newHub
        /home/dgryski/work/src/gocode/src/github.com/dvyukov/go-fuzz/go-fuzz/hub.go:124 +0x10e7
```

**Comment by rlmcpherson** [comment]
Crap, sorry about that. The bounds check is incorrect on line 689. I think it should be ` if i < len(nn)-2 {` I'll open a PR.

**Comment by rlmcpherson** [comment]
I opened #43, which I believe addresses the issue. The append logic was not correct. I haven't been able to reproduce this with the versifier `dump` tests though. @dgryski Do you have an example string that reproduces the panic? It could be good to add to the versifier tests.

**Comment by dgryski** [comment]
I don't think so. I've restarted my fuzzing and unless it was one of the corpus or the crashers I don't have it.
