### ISSUE TITLE
Slave failing master not updating

### ISSUE THREAD

**Issue by Thomasdezeeuw** [dvyukov/go-fuzz#44]
Running with Go `go version devel +aadd84e Sat Jul 18 01:35:25 2015 +0000 windows/amd64`, after a couple of hours of running go-fuzz I get these error messages:

```
2015/07/19 21:09:09 slaves: 0, corpus: 570 (59m8s ago), crashers: 0, restarts: 1
/9999, execs: 355020636 (23109/sec), cover: 490, uptime: 4h16m
2015/07/19 21:09:09 sync call failed: unknown slave
2015/07/19 21:09:12 slaves: 0, corpus: 570 (59m11s ago), crashers: 0, restarts:
1/9999, execs: 355020636 (23104/sec), cover: 490, uptime: 4h16m
2015/07/19 21:09:12 sync call failed: unknown slave
2015/07/19 21:09:14 shutting down...
2015/07/19 21:09:15 sync call failed: unknown slave
```

It seems to me a slave has crashed and the master hasn't updated to remove the slave. The error comes from here: https://github.com/dvyukov/go-fuzz/blob/e7515a616e3e9617e96cf1b30b94a4f3c7738cbc/go-fuzz/hub.go#L166.

**Comment by dvyukov** [comment]
If a slave crashes, it stops sending sync messages, right?: )
This happens when a slave failed to send a sync message in 300 seconds, but then continued to send sync messages. I saw this when a machine goes into deep swapping (because go-fuzz tests start allocating large amounts of memory), as the result slave is actually not scheduled for 300+ seconds. I suspect this is also possible if you hibernate machine and then restore. Is something of the above happened with your machine?

**Comment by Thomasdezeeuw** [comment]
The memory usage was fine, so I don't that is the cause. I find that the messages started to appear after a couple of hours of running, so the hibernation might the problem. I'll run it overnight with hibernation disabled and report back.

**Comment by Thomasdezeeuw** [comment]
Just ran for 10 hours with a problem, with hibernation disabled. So it seems you're right about the hibernation being the problem. Maybe that should be added to the docs somewhere?

**Comment by dvyukov** [comment]
You mean _without_ a problem?

As for a fix, I think we need to make it work more reliably. Currently I just log error but ignore them otherwise. We could e.g. make a slave reconnect and start from scratch, if master says that this slave is unregistered.

**Comment by Thomasdezeeuw** [comment]
I did mean without a problem. Could you point me to the code where should/could be done and and I'll take a crack at it

**Comment by dvyukov** [comment]
go-fuzz/master.go is "server" part of communication.
go-fuzz/hub.go is "client" part of communication. Currently it ignores most communication errors. You can find all communications by searching for "hub.master.Call".

**Comment by Thomasdezeeuw** [comment]
I think this can be closed with https://github.com/dvyukov/go-fuzz/pull/47. But as noted in the commit message errors should be handled a little better, but that could be another issue.
