### ISSUE TITLE
"failed to scan dir '/Users/kamil/go/pkg/include'"

### ISSUE THREAD

**Issue by kisielk** [dvyukov/go-fuzz#5]
I'm trying out go-fuzz for github.com/gorilla/securecookie.

During `go-fuzz-build github.com/gorilla/securecookie/fuzz` I get this error: 

```
failed to scan dir '/Users/kamil/go/pkg/include': open /Users/kamil/go/pkg/include: no such file or directory
```

Not sure why it's looking for an "include" pkg?

Using OS X 10.10 and Go 1.4.1

The fuzz code is available here: https://github.com/gorilla/securecookie/blob/fuzz/fuzz/fuzz.go

**Comment by andrewchambers** [comment]
Can you get the builtin examples to work? test those out. I had a similar error which was fixed by setting GOROOT, so try the build with an explicit GOROOT set too.

**Comment by kisielk** [comment]
hm, `go-fuzz-build github.com/dvyukov/go-fuzz/examples/png` doesn't work either. I do have GOROOT set since I built go in `$HOME/go`

**Comment by andrewchambers** [comment]
Wait for Dimitry to reply,

btw, GOROOT does not normally need to be set if you build the source yourself.

**Comment by kisielk** [comment]
Well, without GOROOT I get the error "GOROOT env var is not set, set it to Go installation dir"  :)

But I also set it anyway since I have some other env vars and scripts that use it, especially since I often run the latest release as well as tip and switch between them.

**Comment by andrewchambers** [comment]
Oh - unrelated, but i have been using Go for a few years, and i use tip. I have never had to set GOROOT once except for using this tool.

**Comment by dvyukov** [comment]
@kisielk the following commit should fix the failure you see:
https://github.com/dvyukov/go-fuzz/commit/6b491bdbfd2aec6643e5f912d437df9a6986f06b
I never tested it on go1.4 before...
@andrewchambers I also added logic to infer GOROOT from go command location, I guess people don't set it.

**Comment by kisielk** [comment]
Works great now, thanks.

**Comment by dvyukov** [comment]
@kisielk 
I've just merged lots of work in progress from sonar branch into master. This adds lots of goodness to go-fuzz. Consider rerunning your existing tests on master head over night. Thanks.
