### ISSUE TITLE
crashers format unclear

### ISSUE THREAD

**Issue by tschottdorf** [dvyukov/go-fuzz#52]
according to the readme, the file without suffix should have the input. However, I repeatedly see the suffixless (and quoted) file contain "SELECT", whereas the corresponding `.output` file contains something along the lines of "SELECT*FROM F group by-0-1,0-1,0-1,0-1,x-1,0-1" created from

```go
func Fuzz(data []byte) int {
	sql := string(data)
	fmt.Println(sql)
```

Shouldn't the above code's output match the suffixless file (mod quoting)?

Example instance here: 
https://github.com/tschottdorf/cockroach/commit/4f259313858d97bb7ccc24ad73bbb4d41a74c0a3

**Comment by tschottdorf** [comment]
actually just saw something; let me reinvestigate before I reopen.

**Comment by tschottdorf** [comment]
updated the commit linked to above for clarity.

**Comment by dvyukov** [comment]
This is caused by the fact that output is not updated after input minimization. That is, go-fuzz captures crash output, then minimizes input, then stores minimized input along with original output.
I was beaten by this several times as well.

**Comment by tschottdorf** [comment]
thanks for clarifying.

**Comment by dvyukov** [comment]
wait, it is something we need to fix, this is confusing, and there is no reason to have this confusing behavior
we just need to update output after minimization
