### ISSUE TITLE
cover: 2746

### ISSUE THREAD

**Issue by tschottdorf** [dvyukov/go-fuzz#53]
the README examples have a coverage value which looks like a percentage (`13%`). In my runs I see something like

`cover: 2746, uptime: 1m21s`

which I can't make sense of given the information in the README. So likely one of the two needs to be updated.

**Comment by dvyukov** [comment]
Fixed. I've updated example output and description to:

```
cover is number of bits set in a hashed coverage bitmap, if this number
grows fuzzer uncovers new lines of code; size of the bitmap is 64K; ideally cover
value should be less than ~5000, otherwise fuzzer can miss new interesting inputs
due to hash collisions.
```

Thanks
