### ISSUE TITLE
fuzzing github.com/andybalholm/cascadia crashes versifier

### ISSUE THREAD

**Issue by andybalholm** [dvyukov/go-fuzz#55]
When I try to fuzz the CSS selector parsing code in github.com/andybalholm/cascadia, I get the following panic:

panic: runtime error: slice bounds out of range

goroutine 28 [running]:
github.com/dvyukov/go-fuzz/go-fuzz/versifier.structureKeyValue(0xc820328180, 0x2, 0x2, 0x0, 0x0, 0x0)
	/Users/andy/src/github.com/dvyukov/go-fuzz/go-fuzz/versifier/versifier.go:696 +0x489
github.com/dvyukov/go-fuzz/go-fuzz/versifier.structure(0xc820328180, 0x2, 0x2, 0x0, 0x0, 0x0)
	/Users/andy/src/github.com/dvyukov/go-fuzz/go-fuzz/versifier/versifier.go:575 +0xdd
github.com/dvyukov/go-fuzz/go-fuzz/versifier.BuildVerse(0xc82027a1b0, 0xc82020a960, 0x6, 0x6, 0x10000)
	/Users/andy/src/github.com/dvyukov/go-fuzz/go-fuzz/versifier/versifier.go:55 +0x1b9
main.(*Hub).loop(0xc820224100)
	/Users/andy/src/github.com/dvyukov/go-fuzz/go-fuzz/hub.go:236 +0x1c2c
created by main.newHub
	/Users/andy/src/github.com/dvyukov/go-fuzz/go-fuzz/hub.go:115 +0xe83

**Comment by dgryski** [comment]
Can you make sure your go-fuzz is up-to-date and includes https://github.com/dvyukov/go-fuzz/commit/401c62564e8a76817cf3ecbf708dc00944db20e8 ?

**Comment by andybalholm** [comment]
Yes, it includes that commit. And now I just pulled the latest changes and tried again. I still get the panic.

**Comment by dgryski** [comment]
cc @rlmcpherson

**Comment by msiebuhr** [comment]
I get a lot of similar crashes when trying go-fuzz on Prometheus' parser (see https://github.com/prometheus/prometheus/issues/667).

If I reduce the included example to fuzz just one of the Parser-functions, the crashes tend to be more frequent than if I fuzz all (as written out in the example). Once I re-run it a few times, it stops crashing...

**Comment by rlmcpherson** [comment]
@dgryski I'll try to replicate it with the Prometheus tests.

**Comment by rlmcpherson** [comment]
@andybalholm I haven't been able to reproduce the panic using your promql fuzzing code here https://github.com/prometheus/prometheus/issues/667#issuecomment-125750642 either with all enabled or just one of them. Is there an initial corpus that reliably causes crashes?

**Comment by andybalholm** [comment]
@rlmcpherson I think you're getting us mixed up. I'm the one with Cascadia, and @msiebuhr is the one with Prometheus.

**Comment by rlmcpherson** [comment]
@andybalholm Yes, my mistake, that question was for @msiebuhr

**Comment by rlmcpherson** [comment]
Nevermind, fuzzing the versifier found the inputs that caused the panic easily. I should have done that earlier. :smiley: I'm still testing but should have a PR soon.
