### ISSUE TITLE
Allow fuzzing multiple functions

### ISSUE THREAD

**Issue by msiebuhr** [dvyukov/go-fuzz#60]
In Prometheus' [promql-package](http://godoc.org/github.com/prometheus/prometheus/promql), there is four distinct parsers, all of which I'd like to fuzz.

Right now, I wrote all four of them into one `Fuzz`-function (see https://github.com/prometheus/prometheus/issues/667#issuecomment-125750642), but then I have to look through the traces to see which of these actually failed (and why).

Would it be possible to do something similar to the testing-package w. `FuzzXXXX(in []byte) int`? to allow fuzzing different parts of the system in one go?

**Comment by msiebuhr** [comment]
Ahh. I now see that `go-fuzz-build` allows me to set the fuzzing function. But perhaps that could be built into the tool itself?

**Comment by dvyukov** [comment]
The go-fuzz-build -f flag does something different. It allows to have several completely independent tests in one package; independent in the sense that they require completely different inputs. See e.g https://github.com/dvyukov/go-fuzz/blob/master/examples/x509/main.go
And you want to test several functions on the same inputs.
I would say that what you have is the way to go. Is it really that large hassle to check the panic messages? How many bugs did you discover?
In my experience every bug still takes some signfiicant time to minimize input, minimize code, understand what happen and localize the bug in source code. Analyzing the panic message looks like a small additional to that.
If that is really an issue for you, you can surround every parsing function with defer/recover, catch panic, augment them with additional description and maybe values of some variables and re-panic. Will that work for your case?

**Comment by msiebuhr** [comment]
Good point - hadn't really thought the input-thing through.

The fuzzing uncovered a few hundred crashes, spread all over. I ended up writing a fuzzer for each parser-function w. separate corpuses, which ended up working much better (both wrt. the generated cases and figuring out where they belonged).

That said, I do think the tooling around fuzzing multiple functions in one project could be a bit better. At very least, it looks like everybody will have to write some logic that keeps track of which fuzzer-function works with which input corpuses. I currently have done ad ad-hoc mapping of `FuzzXXX` to workdir `fuzz-data/XXX/`. (That said; I have no clue what to do run-time; I guess the user would have to choose which function to focus on at that point)

**Comment by dvyukov** [comment]
> The fuzzing uncovered a few hundred crashes, spread all over.

Wow. Is it just in all these parsers:
https://github.com/prometheus/prometheus/issues/667#issuecomment-125750642
or in other packages as well? Any chance of adding them to the trophies section:
https://github.com/dvyukov/go-fuzz#trophies
? Maybe in some aggregate form. Both issues and fix commits work.

I looked at your test more closely, and it seems that these parsers accept different input formats. If it is the case, then, yes, it is better to have separate tests with separate corpuses.


> That said, I do think the tooling around fuzzing multiple functions in one project could be a bit better.

Yes. Currently there is just what I implemented very quickly to enable it at all.

> I currently have done ad ad-hoc mapping of FuzzXXX to workdir fuzz-data/XXX/

That's what I do as well.

**Comment by msiebuhr** [comment]
From looking at the crashing inputs, I have a hunch that there's really only a few crashing bugs in there: https://github.com/prometheus/prometheus/issues/940.

I guess you're free to add it to the trophy-case (I've only done drive-by issues in Prometheus, so I hardly speak for the project), but perhaps it's worth waiting until the bugs are actually fixed :)

**Comment by dvyukov** [comment]
go-fuzz does crash deduplication based on panic stack, so at least these hundreds of crashes all have unique crash stacks...
