### ISSUE TITLE
encoding/json

### ISSUE THREAD

**Issue by andrewchambers** [dvyukov/go-fuzz#7]
Have you been fuzzing encoding/json yet? I noticed you worked on gob.

**Comment by dvyukov** [comment]
I fuzzed it for a bit, but found nothing. Maybe it is bad tests or bad corpus, or maybe there are no bugs.

**Comment by andrewchambers** [comment]
I invested a little time in fuzzing it and found nothing (my corpus was github api examples), I currently have 300 dollars of free GCE credit that will expire in 50 days, perhaps I will do more nearer the end if I still have credit.

**Comment by andrewchambers** [comment]
fwiw, the encoding/json package is pretty valuable simply because many servers probably use it for public json api's. It is a good thing finding stuff there isn't easy :)

**Comment by dvyukov** [comment]
@andrewchambers 
I've just merged lots of work in progress from sonar branch into master. This adds lots of goodness to go-fuzz. Consider rerunning your existing tests on master head over night. Thanks.

**Comment by andrewchambers** [comment]
Thanks, I'll let you know if I find anything.
