### ISSUE TITLE
Put examples in another repo

### ISSUE THREAD

**Issue by anacrolix** [dvyukov/go-fuzz#88]
The go-fuzz repository is abnormally large, and takes some time to fetch on poor connections. Perhaps you could move the non-essential assets to another repository?

**Comment by Thomasdezeeuw** [comment]
Maybe the corpus should be removed, but I think the code in the examples are quite usefull.

**Comment by dgryski** [comment]
Removing them from the repo win only shrink the download size if we rewrote history.

**Comment by Thomasdezeeuw** [comment]
True, but I think it will be worth it. Currently the full repo is about 300 MB on disk for me which seems rather big. Remove the examples and the complete git history it's only 1.2 MB.

**Comment by dgryski** [comment]
Indeed.  It looks like the majority of on-disk space is taken up because the corpus files are small, but still take up an entire disk block.

```
<dgryski@kaepora[go-fuzz] \ʕ◔ϖ◔ʔ/ > du -sh .
749M	.
<dgryski@kaepora[go-fuzz] \ʕ◔ϖ◔ʔ/ > git rm -q -r examples
<dgryski@kaepora[go-fuzz] \ʕ◔ϖ◔ʔ/ > git commit -q -m "examples: delete"
<dgryski@kaepora[go-fuzz] \ʕ◔ϖ◔ʔ/ > du -sh .
31M	.


```

**Comment by anacrolix** [comment]
sparseness more apparent this way
```
gopath/src/github.com/dvyukov/go-fuzz$ gdu --apparent-size -sh .
73M	.
gopath/src/github.com/dvyukov/go-fuzz$ gdu -sh .
287M	.
```
But it was originally the transfer size I am concerned with, which is in the order of 22-24MB. https://api.github.com/repos/dvyukov/go-fuzz

**Comment by dgryski** [comment]
Will be obsoleted by https://github.com/dvyukov/go-fuzz/issues/154

**Comment by AlekSi** [comment]
@dvyukov This is done too.
