### ISSUE TITLE
failed to parse package unicode/utf8

### ISSUE THREAD

**Issue by eapache** [dvyukov/go-fuzz#91]
Go 1.5, Ubuntu x64. Tried experimentally adding a simple `Fuzz` method to sarama (https://github.com/Shopify/sarama). `go build` still works fine, but when I try and run `go-fuzz-build` I get the following error:

`failed to parse package unicode/utf8: /tmp/go-fuzz-build000084784/src/unicode/utf8/utf8.go:385:6: expected operand, found 'range' (and 3 more errors)`

**Comment by dgryski** [comment]
``` 
   383	// RuneCountInString is like RuneCount but its input is a string.
   384	func RuneCountInString(s string) (n int) {
   385		for range s {
   386			n++
   387		}
   388		return
   389	}
```

**Comment by dvyukov** [comment]
Hmmm... I cannot reproduce this. I've included "unicode/utf8" import into a test and it is instrumented just fine.
Are you sure you are using latest version of go-fuzz, go-fuzz-build binary is rebuilt, go1.5 is in PATH, etc? If yes, please provide exact repro instructions.

**Comment by eapache** [comment]
Hmm, rebuilding go-fuzz and go-fuzz-build seems to have cleared this up, one of them must have gotten corrupted or something? Or maybe they were picking up an old artifact from a previous version of go, but whatever it was seems to have fixed itself with a rebuild. Sorry for the bother.
